package entity;
import java.math.BigDecimal;
import java.util.Date;

public class BpOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ORDERID
     *
     * @mbggenerated
     */
    private BigDecimal orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.TXID
     *
     * @mbggenerated
     */
    private BigDecimal txid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BANKNO
     *
     * @mbggenerated
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ORDERTYPE
     *
     * @mbggenerated
     */
    private String ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ORDERSTATE
     *
     * @mbggenerated
     */
    private BigDecimal orderstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ACTDATE
     *
     * @mbggenerated
     */
    private Date actdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PAYACNTIDX
     *
     * @mbggenerated
     */
    private String payacntidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PAYNO
     *
     * @mbggenerated
     */
    private String payno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PAYNAME
     *
     * @mbggenerated
     */
    private String payname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PAYAREACODE
     *
     * @mbggenerated
     */
    private String payareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PAYADDRESS
     *
     * @mbggenerated
     */
    private String payaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.EXPLAIN
     *
     * @mbggenerated
     */
    private String explain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECACNTIDX
     *
     * @mbggenerated
     */
    private String recacntidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECNO
     *
     * @mbggenerated
     */
    private String recno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECNAME
     *
     * @mbggenerated
     */
    private String recname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECAREACODE
     *
     * @mbggenerated
     */
    private String recareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECADDRESS
     *
     * @mbggenerated
     */
    private String recaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECBANKNAME
     *
     * @mbggenerated
     */
    private String recbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.CHEQUENUM
     *
     * @mbggenerated
     */
    private String chequenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.CHEQUEPSWD
     *
     * @mbggenerated
     */
    private String chequepswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.INTERBANK
     *
     * @mbggenerated
     */
    private BigDecimal interbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BSKEY
     *
     * @mbggenerated
     */
    private String bskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.EXGCHANNEL
     *
     * @mbggenerated
     */
    private BigDecimal exgchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PID
     *
     * @mbggenerated
     */
    private BigDecimal pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.TRANSSTATE
     *
     * @mbggenerated
     */
    private BigDecimal transstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ERRHANDLE
     *
     * @mbggenerated
     */
    private BigDecimal errhandle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ERRTIMES
     *
     * @mbggenerated
     */
    private BigDecimal errtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ERRMSG
     *
     * @mbggenerated
     */
    private String errmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PRIORID
     *
     * @mbggenerated
     */
    private BigDecimal priorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BUSSTAG
     *
     * @mbggenerated
     */
    private BigDecimal busstag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.EXECFLAG
     *
     * @mbggenerated
     */
    private BigDecimal execflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.TALLYKEY
     *
     * @mbggenerated
     */
    private String tallykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.FINGERPRINT
     *
     * @mbggenerated
     */
    private String fingerprint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.LASTUPDATETIME
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.LASTEXGTIME
     *
     * @mbggenerated
     */
    private Date lastexgtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BDEX
     *
     * @mbggenerated
     */
    private BigDecimal bdex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BPVERSION
     *
     * @mbggenerated
     */
    private BigDecimal bpversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.RECVERSION
     *
     * @mbggenerated
     */
    private BigDecimal recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.DUP_GRADE
     *
     * @mbggenerated
     */
    private BigDecimal dupGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.PERSONFLAG
     *
     * @mbggenerated
     */
    private BigDecimal personflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.URGENTFLAG
     *
     * @mbggenerated
     */
    private BigDecimal urgentflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.CONTRACTNO
     *
     * @mbggenerated
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BUSINESSNO
     *
     * @mbggenerated
     */
    private String businessno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ORGANIZNO
     *
     * @mbggenerated
     */
    private String organizno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.ERPCODE
     *
     * @mbggenerated
     */
    private String erpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.REPEATRESOLVE
     *
     * @mbggenerated
     */
    private BigDecimal repeatresolve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BATCHFLAG
     *
     * @mbggenerated
     */
    private BigDecimal batchflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_ORDER.BATCHNUM
     *
     * @mbggenerated
     */
    private BigDecimal batchnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ORDERID
     *
     * @return the value of BP_ORDER.ORDERID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ORDERID
     *
     * @param orderid the value for BP_ORDER.ORDERID
     *
     * @mbggenerated
     */
    public void setOrderid(BigDecimal orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.TXID
     *
     * @return the value of BP_ORDER.TXID
     *
     * @mbggenerated
     */
    public BigDecimal getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.TXID
     *
     * @param txid the value for BP_ORDER.TXID
     *
     * @mbggenerated
     */
    public void setTxid(BigDecimal txid) {
        this.txid = txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BANKNO
     *
     * @return the value of BP_ORDER.BANKNO
     *
     * @mbggenerated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BANKNO
     *
     * @param bankno the value for BP_ORDER.BANKNO
     *
     * @mbggenerated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ORDERTYPE
     *
     * @return the value of BP_ORDER.ORDERTYPE
     *
     * @mbggenerated
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ORDERTYPE
     *
     * @param ordertype the value for BP_ORDER.ORDERTYPE
     *
     * @mbggenerated
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ORDERSTATE
     *
     * @return the value of BP_ORDER.ORDERSTATE
     *
     * @mbggenerated
     */
    public BigDecimal getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ORDERSTATE
     *
     * @param orderstate the value for BP_ORDER.ORDERSTATE
     *
     * @mbggenerated
     */
    public void setOrderstate(BigDecimal orderstate) {
        this.orderstate = orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ACTDATE
     *
     * @return the value of BP_ORDER.ACTDATE
     *
     * @mbggenerated
     */
    public Date getActdate() {
        return actdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ACTDATE
     *
     * @param actdate the value for BP_ORDER.ACTDATE
     *
     * @mbggenerated
     */
    public void setActdate(Date actdate) {
        this.actdate = actdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PAYACNTIDX
     *
     * @return the value of BP_ORDER.PAYACNTIDX
     *
     * @mbggenerated
     */
    public String getPayacntidx() {
        return payacntidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PAYACNTIDX
     *
     * @param payacntidx the value for BP_ORDER.PAYACNTIDX
     *
     * @mbggenerated
     */
    public void setPayacntidx(String payacntidx) {
        this.payacntidx = payacntidx == null ? null : payacntidx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PAYNO
     *
     * @return the value of BP_ORDER.PAYNO
     *
     * @mbggenerated
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PAYNO
     *
     * @param payno the value for BP_ORDER.PAYNO
     *
     * @mbggenerated
     */
    public void setPayno(String payno) {
        this.payno = payno == null ? null : payno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PAYNAME
     *
     * @return the value of BP_ORDER.PAYNAME
     *
     * @mbggenerated
     */
    public String getPayname() {
        return payname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PAYNAME
     *
     * @param payname the value for BP_ORDER.PAYNAME
     *
     * @mbggenerated
     */
    public void setPayname(String payname) {
        this.payname = payname == null ? null : payname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PAYAREACODE
     *
     * @return the value of BP_ORDER.PAYAREACODE
     *
     * @mbggenerated
     */
    public String getPayareacode() {
        return payareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PAYAREACODE
     *
     * @param payareacode the value for BP_ORDER.PAYAREACODE
     *
     * @mbggenerated
     */
    public void setPayareacode(String payareacode) {
        this.payareacode = payareacode == null ? null : payareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PAYADDRESS
     *
     * @return the value of BP_ORDER.PAYADDRESS
     *
     * @mbggenerated
     */
    public String getPayaddress() {
        return payaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PAYADDRESS
     *
     * @param payaddress the value for BP_ORDER.PAYADDRESS
     *
     * @mbggenerated
     */
    public void setPayaddress(String payaddress) {
        this.payaddress = payaddress == null ? null : payaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.AMOUNT
     *
     * @return the value of BP_ORDER.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.AMOUNT
     *
     * @param amount the value for BP_ORDER.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.EXPLAIN
     *
     * @return the value of BP_ORDER.EXPLAIN
     *
     * @mbggenerated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.EXPLAIN
     *
     * @param explain the value for BP_ORDER.EXPLAIN
     *
     * @mbggenerated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECACNTIDX
     *
     * @return the value of BP_ORDER.RECACNTIDX
     *
     * @mbggenerated
     */
    public String getRecacntidx() {
        return recacntidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECACNTIDX
     *
     * @param recacntidx the value for BP_ORDER.RECACNTIDX
     *
     * @mbggenerated
     */
    public void setRecacntidx(String recacntidx) {
        this.recacntidx = recacntidx == null ? null : recacntidx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECNO
     *
     * @return the value of BP_ORDER.RECNO
     *
     * @mbggenerated
     */
    public String getRecno() {
        return recno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECNO
     *
     * @param recno the value for BP_ORDER.RECNO
     *
     * @mbggenerated
     */
    public void setRecno(String recno) {
        this.recno = recno == null ? null : recno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECNAME
     *
     * @return the value of BP_ORDER.RECNAME
     *
     * @mbggenerated
     */
    public String getRecname() {
        return recname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECNAME
     *
     * @param recname the value for BP_ORDER.RECNAME
     *
     * @mbggenerated
     */
    public void setRecname(String recname) {
        this.recname = recname == null ? null : recname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECAREACODE
     *
     * @return the value of BP_ORDER.RECAREACODE
     *
     * @mbggenerated
     */
    public String getRecareacode() {
        return recareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECAREACODE
     *
     * @param recareacode the value for BP_ORDER.RECAREACODE
     *
     * @mbggenerated
     */
    public void setRecareacode(String recareacode) {
        this.recareacode = recareacode == null ? null : recareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECADDRESS
     *
     * @return the value of BP_ORDER.RECADDRESS
     *
     * @mbggenerated
     */
    public String getRecaddress() {
        return recaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECADDRESS
     *
     * @param recaddress the value for BP_ORDER.RECADDRESS
     *
     * @mbggenerated
     */
    public void setRecaddress(String recaddress) {
        this.recaddress = recaddress == null ? null : recaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECBANKNAME
     *
     * @return the value of BP_ORDER.RECBANKNAME
     *
     * @mbggenerated
     */
    public String getRecbankname() {
        return recbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECBANKNAME
     *
     * @param recbankname the value for BP_ORDER.RECBANKNAME
     *
     * @mbggenerated
     */
    public void setRecbankname(String recbankname) {
        this.recbankname = recbankname == null ? null : recbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.CHEQUENUM
     *
     * @return the value of BP_ORDER.CHEQUENUM
     *
     * @mbggenerated
     */
    public String getChequenum() {
        return chequenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.CHEQUENUM
     *
     * @param chequenum the value for BP_ORDER.CHEQUENUM
     *
     * @mbggenerated
     */
    public void setChequenum(String chequenum) {
        this.chequenum = chequenum == null ? null : chequenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.CHEQUEPSWD
     *
     * @return the value of BP_ORDER.CHEQUEPSWD
     *
     * @mbggenerated
     */
    public String getChequepswd() {
        return chequepswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.CHEQUEPSWD
     *
     * @param chequepswd the value for BP_ORDER.CHEQUEPSWD
     *
     * @mbggenerated
     */
    public void setChequepswd(String chequepswd) {
        this.chequepswd = chequepswd == null ? null : chequepswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.INTERBANK
     *
     * @return the value of BP_ORDER.INTERBANK
     *
     * @mbggenerated
     */
    public BigDecimal getInterbank() {
        return interbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.INTERBANK
     *
     * @param interbank the value for BP_ORDER.INTERBANK
     *
     * @mbggenerated
     */
    public void setInterbank(BigDecimal interbank) {
        this.interbank = interbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BSKEY
     *
     * @return the value of BP_ORDER.BSKEY
     *
     * @mbggenerated
     */
    public String getBskey() {
        return bskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BSKEY
     *
     * @param bskey the value for BP_ORDER.BSKEY
     *
     * @mbggenerated
     */
    public void setBskey(String bskey) {
        this.bskey = bskey == null ? null : bskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.EXGCHANNEL
     *
     * @return the value of BP_ORDER.EXGCHANNEL
     *
     * @mbggenerated
     */
    public BigDecimal getExgchannel() {
        return exgchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.EXGCHANNEL
     *
     * @param exgchannel the value for BP_ORDER.EXGCHANNEL
     *
     * @mbggenerated
     */
    public void setExgchannel(BigDecimal exgchannel) {
        this.exgchannel = exgchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PID
     *
     * @return the value of BP_ORDER.PID
     *
     * @mbggenerated
     */
    public BigDecimal getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PID
     *
     * @param pid the value for BP_ORDER.PID
     *
     * @mbggenerated
     */
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.TRANSSTATE
     *
     * @return the value of BP_ORDER.TRANSSTATE
     *
     * @mbggenerated
     */
    public BigDecimal getTransstate() {
        return transstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.TRANSSTATE
     *
     * @param transstate the value for BP_ORDER.TRANSSTATE
     *
     * @mbggenerated
     */
    public void setTransstate(BigDecimal transstate) {
        this.transstate = transstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ERRHANDLE
     *
     * @return the value of BP_ORDER.ERRHANDLE
     *
     * @mbggenerated
     */
    public BigDecimal getErrhandle() {
        return errhandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ERRHANDLE
     *
     * @param errhandle the value for BP_ORDER.ERRHANDLE
     *
     * @mbggenerated
     */
    public void setErrhandle(BigDecimal errhandle) {
        this.errhandle = errhandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ERRTIMES
     *
     * @return the value of BP_ORDER.ERRTIMES
     *
     * @mbggenerated
     */
    public BigDecimal getErrtimes() {
        return errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ERRTIMES
     *
     * @param errtimes the value for BP_ORDER.ERRTIMES
     *
     * @mbggenerated
     */
    public void setErrtimes(BigDecimal errtimes) {
        this.errtimes = errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ERRMSG
     *
     * @return the value of BP_ORDER.ERRMSG
     *
     * @mbggenerated
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ERRMSG
     *
     * @param errmsg the value for BP_ORDER.ERRMSG
     *
     * @mbggenerated
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PRIORID
     *
     * @return the value of BP_ORDER.PRIORID
     *
     * @mbggenerated
     */
    public BigDecimal getPriorid() {
        return priorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PRIORID
     *
     * @param priorid the value for BP_ORDER.PRIORID
     *
     * @mbggenerated
     */
    public void setPriorid(BigDecimal priorid) {
        this.priorid = priorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BUSSTAG
     *
     * @return the value of BP_ORDER.BUSSTAG
     *
     * @mbggenerated
     */
    public BigDecimal getBusstag() {
        return busstag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BUSSTAG
     *
     * @param busstag the value for BP_ORDER.BUSSTAG
     *
     * @mbggenerated
     */
    public void setBusstag(BigDecimal busstag) {
        this.busstag = busstag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.EXECFLAG
     *
     * @return the value of BP_ORDER.EXECFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getExecflag() {
        return execflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.EXECFLAG
     *
     * @param execflag the value for BP_ORDER.EXECFLAG
     *
     * @mbggenerated
     */
    public void setExecflag(BigDecimal execflag) {
        this.execflag = execflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.TALLYKEY
     *
     * @return the value of BP_ORDER.TALLYKEY
     *
     * @mbggenerated
     */
    public String getTallykey() {
        return tallykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.TALLYKEY
     *
     * @param tallykey the value for BP_ORDER.TALLYKEY
     *
     * @mbggenerated
     */
    public void setTallykey(String tallykey) {
        this.tallykey = tallykey == null ? null : tallykey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.FINGERPRINT
     *
     * @return the value of BP_ORDER.FINGERPRINT
     *
     * @mbggenerated
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.FINGERPRINT
     *
     * @param fingerprint the value for BP_ORDER.FINGERPRINT
     *
     * @mbggenerated
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint == null ? null : fingerprint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.CREATETIME
     *
     * @return the value of BP_ORDER.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.CREATETIME
     *
     * @param createtime the value for BP_ORDER.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.LASTUPDATETIME
     *
     * @return the value of BP_ORDER.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.LASTUPDATETIME
     *
     * @param lastupdatetime the value for BP_ORDER.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.LASTEXGTIME
     *
     * @return the value of BP_ORDER.LASTEXGTIME
     *
     * @mbggenerated
     */
    public Date getLastexgtime() {
        return lastexgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.LASTEXGTIME
     *
     * @param lastexgtime the value for BP_ORDER.LASTEXGTIME
     *
     * @mbggenerated
     */
    public void setLastexgtime(Date lastexgtime) {
        this.lastexgtime = lastexgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BDEX
     *
     * @return the value of BP_ORDER.BDEX
     *
     * @mbggenerated
     */
    public BigDecimal getBdex() {
        return bdex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BDEX
     *
     * @param bdex the value for BP_ORDER.BDEX
     *
     * @mbggenerated
     */
    public void setBdex(BigDecimal bdex) {
        this.bdex = bdex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BPVERSION
     *
     * @return the value of BP_ORDER.BPVERSION
     *
     * @mbggenerated
     */
    public BigDecimal getBpversion() {
        return bpversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BPVERSION
     *
     * @param bpversion the value for BP_ORDER.BPVERSION
     *
     * @mbggenerated
     */
    public void setBpversion(BigDecimal bpversion) {
        this.bpversion = bpversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.RECVERSION
     *
     * @return the value of BP_ORDER.RECVERSION
     *
     * @mbggenerated
     */
    public BigDecimal getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.RECVERSION
     *
     * @param recversion the value for BP_ORDER.RECVERSION
     *
     * @mbggenerated
     */
    public void setRecversion(BigDecimal recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.DUP_GRADE
     *
     * @return the value of BP_ORDER.DUP_GRADE
     *
     * @mbggenerated
     */
    public BigDecimal getDupGrade() {
        return dupGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.DUP_GRADE
     *
     * @param dupGrade the value for BP_ORDER.DUP_GRADE
     *
     * @mbggenerated
     */
    public void setDupGrade(BigDecimal dupGrade) {
        this.dupGrade = dupGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.PERSONFLAG
     *
     * @return the value of BP_ORDER.PERSONFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getPersonflag() {
        return personflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.PERSONFLAG
     *
     * @param personflag the value for BP_ORDER.PERSONFLAG
     *
     * @mbggenerated
     */
    public void setPersonflag(BigDecimal personflag) {
        this.personflag = personflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.URGENTFLAG
     *
     * @return the value of BP_ORDER.URGENTFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getUrgentflag() {
        return urgentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.URGENTFLAG
     *
     * @param urgentflag the value for BP_ORDER.URGENTFLAG
     *
     * @mbggenerated
     */
    public void setUrgentflag(BigDecimal urgentflag) {
        this.urgentflag = urgentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.CONTRACTNO
     *
     * @return the value of BP_ORDER.CONTRACTNO
     *
     * @mbggenerated
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.CONTRACTNO
     *
     * @param contractno the value for BP_ORDER.CONTRACTNO
     *
     * @mbggenerated
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BUSINESSNO
     *
     * @return the value of BP_ORDER.BUSINESSNO
     *
     * @mbggenerated
     */
    public String getBusinessno() {
        return businessno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BUSINESSNO
     *
     * @param businessno the value for BP_ORDER.BUSINESSNO
     *
     * @mbggenerated
     */
    public void setBusinessno(String businessno) {
        this.businessno = businessno == null ? null : businessno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ORGANIZNO
     *
     * @return the value of BP_ORDER.ORGANIZNO
     *
     * @mbggenerated
     */
    public String getOrganizno() {
        return organizno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ORGANIZNO
     *
     * @param organizno the value for BP_ORDER.ORGANIZNO
     *
     * @mbggenerated
     */
    public void setOrganizno(String organizno) {
        this.organizno = organizno == null ? null : organizno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.ERPCODE
     *
     * @return the value of BP_ORDER.ERPCODE
     *
     * @mbggenerated
     */
    public String getErpcode() {
        return erpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.ERPCODE
     *
     * @param erpcode the value for BP_ORDER.ERPCODE
     *
     * @mbggenerated
     */
    public void setErpcode(String erpcode) {
        this.erpcode = erpcode == null ? null : erpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.REPEATRESOLVE
     *
     * @return the value of BP_ORDER.REPEATRESOLVE
     *
     * @mbggenerated
     */
    public BigDecimal getRepeatresolve() {
        return repeatresolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.REPEATRESOLVE
     *
     * @param repeatresolve the value for BP_ORDER.REPEATRESOLVE
     *
     * @mbggenerated
     */
    public void setRepeatresolve(BigDecimal repeatresolve) {
        this.repeatresolve = repeatresolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BATCHFLAG
     *
     * @return the value of BP_ORDER.BATCHFLAG
     *
     * @mbggenerated
     */
    public BigDecimal getBatchflag() {
        return batchflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BATCHFLAG
     *
     * @param batchflag the value for BP_ORDER.BATCHFLAG
     *
     * @mbggenerated
     */
    public void setBatchflag(BigDecimal batchflag) {
        this.batchflag = batchflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_ORDER.BATCHNUM
     *
     * @return the value of BP_ORDER.BATCHNUM
     *
     * @mbggenerated
     */
    public BigDecimal getBatchnum() {
        return batchnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_ORDER.BATCHNUM
     *
     * @param batchnum the value for BP_ORDER.BATCHNUM
     *
     * @mbggenerated
     */
    public void setBatchnum(BigDecimal batchnum) {
        this.batchnum = batchnum;
    }
}