package entity;

import java.math.BigDecimal;
import java.util.Date;

public class CltCltInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.TYPE
     *
     * @mbggenerated
     */
    private BigDecimal type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CLTNO
     *
     * @mbggenerated
     */
    private String cltno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.TREENO
     *
     * @mbggenerated
     */
    private String treeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CHINESENAME
     *
     * @mbggenerated
     */
    private String chinesename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ABBREVIATION
     *
     * @mbggenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.OPBANK
     *
     * @mbggenerated
     */
    private String opbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ACNTNO
     *
     * @mbggenerated
     */
    private String acntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.INTERNETSITE
     *
     * @mbggenerated
     */
    private String internetsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.BUSSADDR
     *
     * @mbggenerated
     */
    private String bussaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.POSTCODE
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FAX
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.DEPINCHARGE
     *
     * @mbggenerated
     */
    private String depincharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.DAYOFESTB
     *
     * @mbggenerated
     */
    private Date dayofestb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.INDUSTRY
     *
     * @mbggenerated
     */
    private BigDecimal industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.RANKING
     *
     * @mbggenerated
     */
    private BigDecimal ranking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORGCODE
     *
     * @mbggenerated
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FINANTYPE
     *
     * @mbggenerated
     */
    private BigDecimal finantype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LISENSENO
     *
     * @mbggenerated
     */
    private String lisenseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.TAXREGNO
     *
     * @mbggenerated
     */
    private String taxregno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LOANNO
     *
     * @mbggenerated
     */
    private String loanno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.OPRATETERM
     *
     * @mbggenerated
     */
    private String oprateterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FERC
     *
     * @mbggenerated
     */
    private String ferc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.BUSSSCOPE
     *
     * @mbggenerated
     */
    private String bussscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REGCAPITAL
     *
     * @mbggenerated
     */
    private BigDecimal regcapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CUR
     *
     * @mbggenerated
     */
    private BigDecimal cur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REGADDR
     *
     * @mbggenerated
     */
    private String regaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LEGALPERZIP
     *
     * @mbggenerated
     */
    private String legalperzip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LEGALPER
     *
     * @mbggenerated
     */
    private String legalper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LEGALPERID
     *
     * @mbggenerated
     */
    private String legalperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LEGALPERPHONE
     *
     * @mbggenerated
     */
    private String legalperphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CREDITLEVEL
     *
     * @mbggenerated
     */
    private BigDecimal creditlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.EVALAUTH
     *
     * @mbggenerated
     */
    private String evalauth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.EVALTIME
     *
     * @mbggenerated
     */
    private Date evaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CREDITRATING
     *
     * @mbggenerated
     */
    private BigDecimal creditrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.EXTCLTNO
     *
     * @mbggenerated
     */
    private String extcltno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ISLISTED
     *
     * @mbggenerated
     */
    private BigDecimal islisted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.AREA
     *
     * @mbggenerated
     */
    private BigDecimal area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.COUNTRYCODE
     *
     * @mbggenerated
     */
    private String countrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.INGROUP
     *
     * @mbggenerated
     */
    private String ingroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.NATURE
     *
     * @mbggenerated
     */
    private BigDecimal nature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CORPTYPE
     *
     * @mbggenerated
     */
    private BigDecimal corptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CORSUBTYPE
     *
     * @mbggenerated
     */
    private BigDecimal corsubtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.OTHER
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.BANKNO
     *
     * @mbggenerated
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.STAUTS
     *
     * @mbggenerated
     */
    private BigDecimal stauts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CAUSE
     *
     * @mbggenerated
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ENTERPRISESCALE
     *
     * @mbggenerated
     */
    private BigDecimal enterprisescale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LICENSECODE
     *
     * @mbggenerated
     */
    private String licensecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FINANCIALCODE
     *
     * @mbggenerated
     */
    private String financialcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CLTSTATE
     *
     * @mbggenerated
     */
    private BigDecimal cltstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FINANCIALCONTACT
     *
     * @mbggenerated
     */
    private String financialcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ENDDATE
     *
     * @mbggenerated
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.STOCKCODE
     *
     * @mbggenerated
     */
    private String stockcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.SITEAREA
     *
     * @mbggenerated
     */
    private BigDecimal sitearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.SITETITLE
     *
     * @mbggenerated
     */
    private String sitetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.EMPLOYEESNUM
     *
     * @mbggenerated
     */
    private BigDecimal employeesnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.TAXNUM
     *
     * @mbggenerated
     */
    private String taxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LANDTAXNUM
     *
     * @mbggenerated
     */
    private String landtaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PRODUCTSMAJOR
     *
     * @mbggenerated
     */
    private String productsmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LISTEDPLACE
     *
     * @mbggenerated
     */
    private String listedplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.DISTRICT
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.BORRNATURE
     *
     * @mbggenerated
     */
    private BigDecimal borrnature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.MECCODE
     *
     * @mbggenerated
     */
    private String meccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PROJECTNAME
     *
     * @mbggenerated
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.COMPANTYATTRIBUTE
     *
     * @mbggenerated
     */
    private BigDecimal compantyattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REGIONTEXT
     *
     * @mbggenerated
     */
    private String regiontext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.LEFTFIG_N3
     *
     * @mbggenerated
     */
    private BigDecimal leftfigN3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.RIGHTFIG_N3
     *
     * @mbggenerated
     */
    private BigDecimal rightfigN3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.DEPT_TYPE
     *
     * @mbggenerated
     */
    private String deptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORG_PARENT_ID
     *
     * @mbggenerated
     */
    private String orgParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ROLEGROUPID
     *
     * @mbggenerated
     */
    private BigDecimal rolegroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FINA_PRINCIPAL
     *
     * @mbggenerated
     */
    private String finaPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PRIMARY_ACC_NO
     *
     * @mbggenerated
     */
    private String primaryAccNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CONTACT_PERSON
     *
     * @mbggenerated
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REMARK_
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.SYNC_FLAG
     *
     * @mbggenerated
     */
    private BigDecimal syncFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.SYNC_VERSION
     *
     * @mbggenerated
     */
    private BigDecimal syncVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.AUTH_BY_USER_FLAG
     *
     * @mbggenerated
     */
    private BigDecimal authByUserFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.AGENCY_NO
     *
     * @mbggenerated
     */
    private String agencyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORG_ORDER
     *
     * @mbggenerated
     */
    private BigDecimal orgOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORG_LEVEL
     *
     * @mbggenerated
     */
    private BigDecimal orgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORGCLASSID
     *
     * @mbggenerated
     */
    private Long orgclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.PARENT_ID
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.INSTICREDITCODE
     *
     * @mbggenerated
     */
    private String insticreditcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REGNUMCODE
     *
     * @mbggenerated
     */
    private String regnumcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.APPRONUM
     *
     * @mbggenerated
     */
    private String appronum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORGTYPEDETAIL
     *
     * @mbggenerated
     */
    private String orgtypedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.BCOMMADD
     *
     * @mbggenerated
     */
    private String bcommadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.CLTTYPE
     *
     * @mbggenerated
     */
    private String clttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.ORGTYPE
     *
     * @mbggenerated
     */
    private String orgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.MANAGEBANKCODE
     *
     * @mbggenerated
     */
    private String managebankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.FORTDRTFG
     *
     * @mbggenerated
     */
    private String fortdrtfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLT_CLT_INFO.REGCODE
     *
     * @mbggenerated
     */
    private String regcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ID
     *
     * @return the value of CLT_CLT_INFO.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ID
     *
     * @param id the value for CLT_CLT_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.TYPE
     *
     * @return the value of CLT_CLT_INFO.TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.TYPE
     *
     * @param type the value for CLT_CLT_INFO.TYPE
     *
     * @mbggenerated
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CLTNO
     *
     * @return the value of CLT_CLT_INFO.CLTNO
     *
     * @mbggenerated
     */
    public String getCltno() {
        return cltno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CLTNO
     *
     * @param cltno the value for CLT_CLT_INFO.CLTNO
     *
     * @mbggenerated
     */
    public void setCltno(String cltno) {
        this.cltno = cltno == null ? null : cltno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.TREENO
     *
     * @return the value of CLT_CLT_INFO.TREENO
     *
     * @mbggenerated
     */
    public String getTreeno() {
        return treeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.TREENO
     *
     * @param treeno the value for CLT_CLT_INFO.TREENO
     *
     * @mbggenerated
     */
    public void setTreeno(String treeno) {
        this.treeno = treeno == null ? null : treeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CHINESENAME
     *
     * @return the value of CLT_CLT_INFO.CHINESENAME
     *
     * @mbggenerated
     */
    public String getChinesename() {
        return chinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CHINESENAME
     *
     * @param chinesename the value for CLT_CLT_INFO.CHINESENAME
     *
     * @mbggenerated
     */
    public void setChinesename(String chinesename) {
        this.chinesename = chinesename == null ? null : chinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ABBREVIATION
     *
     * @return the value of CLT_CLT_INFO.ABBREVIATION
     *
     * @mbggenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ABBREVIATION
     *
     * @param abbreviation the value for CLT_CLT_INFO.ABBREVIATION
     *
     * @mbggenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.NAME
     *
     * @return the value of CLT_CLT_INFO.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.NAME
     *
     * @param name the value for CLT_CLT_INFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.OPBANK
     *
     * @return the value of CLT_CLT_INFO.OPBANK
     *
     * @mbggenerated
     */
    public String getOpbank() {
        return opbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.OPBANK
     *
     * @param opbank the value for CLT_CLT_INFO.OPBANK
     *
     * @mbggenerated
     */
    public void setOpbank(String opbank) {
        this.opbank = opbank == null ? null : opbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ACNTNO
     *
     * @return the value of CLT_CLT_INFO.ACNTNO
     *
     * @mbggenerated
     */
    public String getAcntno() {
        return acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ACNTNO
     *
     * @param acntno the value for CLT_CLT_INFO.ACNTNO
     *
     * @mbggenerated
     */
    public void setAcntno(String acntno) {
        this.acntno = acntno == null ? null : acntno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.INTERNETSITE
     *
     * @return the value of CLT_CLT_INFO.INTERNETSITE
     *
     * @mbggenerated
     */
    public String getInternetsite() {
        return internetsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.INTERNETSITE
     *
     * @param internetsite the value for CLT_CLT_INFO.INTERNETSITE
     *
     * @mbggenerated
     */
    public void setInternetsite(String internetsite) {
        this.internetsite = internetsite == null ? null : internetsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PHONE
     *
     * @return the value of CLT_CLT_INFO.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PHONE
     *
     * @param phone the value for CLT_CLT_INFO.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.BUSSADDR
     *
     * @return the value of CLT_CLT_INFO.BUSSADDR
     *
     * @mbggenerated
     */
    public String getBussaddr() {
        return bussaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.BUSSADDR
     *
     * @param bussaddr the value for CLT_CLT_INFO.BUSSADDR
     *
     * @mbggenerated
     */
    public void setBussaddr(String bussaddr) {
        this.bussaddr = bussaddr == null ? null : bussaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.POSTCODE
     *
     * @return the value of CLT_CLT_INFO.POSTCODE
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.POSTCODE
     *
     * @param postcode the value for CLT_CLT_INFO.POSTCODE
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FAX
     *
     * @return the value of CLT_CLT_INFO.FAX
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FAX
     *
     * @param fax the value for CLT_CLT_INFO.FAX
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.DEPINCHARGE
     *
     * @return the value of CLT_CLT_INFO.DEPINCHARGE
     *
     * @mbggenerated
     */
    public String getDepincharge() {
        return depincharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.DEPINCHARGE
     *
     * @param depincharge the value for CLT_CLT_INFO.DEPINCHARGE
     *
     * @mbggenerated
     */
    public void setDepincharge(String depincharge) {
        this.depincharge = depincharge == null ? null : depincharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.DAYOFESTB
     *
     * @return the value of CLT_CLT_INFO.DAYOFESTB
     *
     * @mbggenerated
     */
    public Date getDayofestb() {
        return dayofestb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.DAYOFESTB
     *
     * @param dayofestb the value for CLT_CLT_INFO.DAYOFESTB
     *
     * @mbggenerated
     */
    public void setDayofestb(Date dayofestb) {
        this.dayofestb = dayofestb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.INDUSTRY
     *
     * @return the value of CLT_CLT_INFO.INDUSTRY
     *
     * @mbggenerated
     */
    public BigDecimal getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.INDUSTRY
     *
     * @param industry the value for CLT_CLT_INFO.INDUSTRY
     *
     * @mbggenerated
     */
    public void setIndustry(BigDecimal industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.RANKING
     *
     * @return the value of CLT_CLT_INFO.RANKING
     *
     * @mbggenerated
     */
    public BigDecimal getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.RANKING
     *
     * @param ranking the value for CLT_CLT_INFO.RANKING
     *
     * @mbggenerated
     */
    public void setRanking(BigDecimal ranking) {
        this.ranking = ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORGCODE
     *
     * @return the value of CLT_CLT_INFO.ORGCODE
     *
     * @mbggenerated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORGCODE
     *
     * @param orgcode the value for CLT_CLT_INFO.ORGCODE
     *
     * @mbggenerated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FINANTYPE
     *
     * @return the value of CLT_CLT_INFO.FINANTYPE
     *
     * @mbggenerated
     */
    public BigDecimal getFinantype() {
        return finantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FINANTYPE
     *
     * @param finantype the value for CLT_CLT_INFO.FINANTYPE
     *
     * @mbggenerated
     */
    public void setFinantype(BigDecimal finantype) {
        this.finantype = finantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LISENSENO
     *
     * @return the value of CLT_CLT_INFO.LISENSENO
     *
     * @mbggenerated
     */
    public String getLisenseno() {
        return lisenseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LISENSENO
     *
     * @param lisenseno the value for CLT_CLT_INFO.LISENSENO
     *
     * @mbggenerated
     */
    public void setLisenseno(String lisenseno) {
        this.lisenseno = lisenseno == null ? null : lisenseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.TAXREGNO
     *
     * @return the value of CLT_CLT_INFO.TAXREGNO
     *
     * @mbggenerated
     */
    public String getTaxregno() {
        return taxregno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.TAXREGNO
     *
     * @param taxregno the value for CLT_CLT_INFO.TAXREGNO
     *
     * @mbggenerated
     */
    public void setTaxregno(String taxregno) {
        this.taxregno = taxregno == null ? null : taxregno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LOANNO
     *
     * @return the value of CLT_CLT_INFO.LOANNO
     *
     * @mbggenerated
     */
    public String getLoanno() {
        return loanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LOANNO
     *
     * @param loanno the value for CLT_CLT_INFO.LOANNO
     *
     * @mbggenerated
     */
    public void setLoanno(String loanno) {
        this.loanno = loanno == null ? null : loanno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.OPRATETERM
     *
     * @return the value of CLT_CLT_INFO.OPRATETERM
     *
     * @mbggenerated
     */
    public String getOprateterm() {
        return oprateterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.OPRATETERM
     *
     * @param oprateterm the value for CLT_CLT_INFO.OPRATETERM
     *
     * @mbggenerated
     */
    public void setOprateterm(String oprateterm) {
        this.oprateterm = oprateterm == null ? null : oprateterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FERC
     *
     * @return the value of CLT_CLT_INFO.FERC
     *
     * @mbggenerated
     */
    public String getFerc() {
        return ferc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FERC
     *
     * @param ferc the value for CLT_CLT_INFO.FERC
     *
     * @mbggenerated
     */
    public void setFerc(String ferc) {
        this.ferc = ferc == null ? null : ferc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.BUSSSCOPE
     *
     * @return the value of CLT_CLT_INFO.BUSSSCOPE
     *
     * @mbggenerated
     */
    public String getBussscope() {
        return bussscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.BUSSSCOPE
     *
     * @param bussscope the value for CLT_CLT_INFO.BUSSSCOPE
     *
     * @mbggenerated
     */
    public void setBussscope(String bussscope) {
        this.bussscope = bussscope == null ? null : bussscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REGCAPITAL
     *
     * @return the value of CLT_CLT_INFO.REGCAPITAL
     *
     * @mbggenerated
     */
    public BigDecimal getRegcapital() {
        return regcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REGCAPITAL
     *
     * @param regcapital the value for CLT_CLT_INFO.REGCAPITAL
     *
     * @mbggenerated
     */
    public void setRegcapital(BigDecimal regcapital) {
        this.regcapital = regcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CUR
     *
     * @return the value of CLT_CLT_INFO.CUR
     *
     * @mbggenerated
     */
    public BigDecimal getCur() {
        return cur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CUR
     *
     * @param cur the value for CLT_CLT_INFO.CUR
     *
     * @mbggenerated
     */
    public void setCur(BigDecimal cur) {
        this.cur = cur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REGADDR
     *
     * @return the value of CLT_CLT_INFO.REGADDR
     *
     * @mbggenerated
     */
    public String getRegaddr() {
        return regaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REGADDR
     *
     * @param regaddr the value for CLT_CLT_INFO.REGADDR
     *
     * @mbggenerated
     */
    public void setRegaddr(String regaddr) {
        this.regaddr = regaddr == null ? null : regaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LEGALPERZIP
     *
     * @return the value of CLT_CLT_INFO.LEGALPERZIP
     *
     * @mbggenerated
     */
    public String getLegalperzip() {
        return legalperzip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LEGALPERZIP
     *
     * @param legalperzip the value for CLT_CLT_INFO.LEGALPERZIP
     *
     * @mbggenerated
     */
    public void setLegalperzip(String legalperzip) {
        this.legalperzip = legalperzip == null ? null : legalperzip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LEGALPER
     *
     * @return the value of CLT_CLT_INFO.LEGALPER
     *
     * @mbggenerated
     */
    public String getLegalper() {
        return legalper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LEGALPER
     *
     * @param legalper the value for CLT_CLT_INFO.LEGALPER
     *
     * @mbggenerated
     */
    public void setLegalper(String legalper) {
        this.legalper = legalper == null ? null : legalper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LEGALPERID
     *
     * @return the value of CLT_CLT_INFO.LEGALPERID
     *
     * @mbggenerated
     */
    public String getLegalperid() {
        return legalperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LEGALPERID
     *
     * @param legalperid the value for CLT_CLT_INFO.LEGALPERID
     *
     * @mbggenerated
     */
    public void setLegalperid(String legalperid) {
        this.legalperid = legalperid == null ? null : legalperid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LEGALPERPHONE
     *
     * @return the value of CLT_CLT_INFO.LEGALPERPHONE
     *
     * @mbggenerated
     */
    public String getLegalperphone() {
        return legalperphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LEGALPERPHONE
     *
     * @param legalperphone the value for CLT_CLT_INFO.LEGALPERPHONE
     *
     * @mbggenerated
     */
    public void setLegalperphone(String legalperphone) {
        this.legalperphone = legalperphone == null ? null : legalperphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CREDITLEVEL
     *
     * @return the value of CLT_CLT_INFO.CREDITLEVEL
     *
     * @mbggenerated
     */
    public BigDecimal getCreditlevel() {
        return creditlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CREDITLEVEL
     *
     * @param creditlevel the value for CLT_CLT_INFO.CREDITLEVEL
     *
     * @mbggenerated
     */
    public void setCreditlevel(BigDecimal creditlevel) {
        this.creditlevel = creditlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.EVALAUTH
     *
     * @return the value of CLT_CLT_INFO.EVALAUTH
     *
     * @mbggenerated
     */
    public String getEvalauth() {
        return evalauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.EVALAUTH
     *
     * @param evalauth the value for CLT_CLT_INFO.EVALAUTH
     *
     * @mbggenerated
     */
    public void setEvalauth(String evalauth) {
        this.evalauth = evalauth == null ? null : evalauth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.EVALTIME
     *
     * @return the value of CLT_CLT_INFO.EVALTIME
     *
     * @mbggenerated
     */
    public Date getEvaltime() {
        return evaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.EVALTIME
     *
     * @param evaltime the value for CLT_CLT_INFO.EVALTIME
     *
     * @mbggenerated
     */
    public void setEvaltime(Date evaltime) {
        this.evaltime = evaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CREDITRATING
     *
     * @return the value of CLT_CLT_INFO.CREDITRATING
     *
     * @mbggenerated
     */
    public BigDecimal getCreditrating() {
        return creditrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CREDITRATING
     *
     * @param creditrating the value for CLT_CLT_INFO.CREDITRATING
     *
     * @mbggenerated
     */
    public void setCreditrating(BigDecimal creditrating) {
        this.creditrating = creditrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.EXTCLTNO
     *
     * @return the value of CLT_CLT_INFO.EXTCLTNO
     *
     * @mbggenerated
     */
    public String getExtcltno() {
        return extcltno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.EXTCLTNO
     *
     * @param extcltno the value for CLT_CLT_INFO.EXTCLTNO
     *
     * @mbggenerated
     */
    public void setExtcltno(String extcltno) {
        this.extcltno = extcltno == null ? null : extcltno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ISLISTED
     *
     * @return the value of CLT_CLT_INFO.ISLISTED
     *
     * @mbggenerated
     */
    public BigDecimal getIslisted() {
        return islisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ISLISTED
     *
     * @param islisted the value for CLT_CLT_INFO.ISLISTED
     *
     * @mbggenerated
     */
    public void setIslisted(BigDecimal islisted) {
        this.islisted = islisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.AREA
     *
     * @return the value of CLT_CLT_INFO.AREA
     *
     * @mbggenerated
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.AREA
     *
     * @param area the value for CLT_CLT_INFO.AREA
     *
     * @mbggenerated
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.COUNTRYCODE
     *
     * @return the value of CLT_CLT_INFO.COUNTRYCODE
     *
     * @mbggenerated
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.COUNTRYCODE
     *
     * @param countrycode the value for CLT_CLT_INFO.COUNTRYCODE
     *
     * @mbggenerated
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.INGROUP
     *
     * @return the value of CLT_CLT_INFO.INGROUP
     *
     * @mbggenerated
     */
    public String getIngroup() {
        return ingroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.INGROUP
     *
     * @param ingroup the value for CLT_CLT_INFO.INGROUP
     *
     * @mbggenerated
     */
    public void setIngroup(String ingroup) {
        this.ingroup = ingroup == null ? null : ingroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.NATURE
     *
     * @return the value of CLT_CLT_INFO.NATURE
     *
     * @mbggenerated
     */
    public BigDecimal getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.NATURE
     *
     * @param nature the value for CLT_CLT_INFO.NATURE
     *
     * @mbggenerated
     */
    public void setNature(BigDecimal nature) {
        this.nature = nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CORPTYPE
     *
     * @return the value of CLT_CLT_INFO.CORPTYPE
     *
     * @mbggenerated
     */
    public BigDecimal getCorptype() {
        return corptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CORPTYPE
     *
     * @param corptype the value for CLT_CLT_INFO.CORPTYPE
     *
     * @mbggenerated
     */
    public void setCorptype(BigDecimal corptype) {
        this.corptype = corptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CORSUBTYPE
     *
     * @return the value of CLT_CLT_INFO.CORSUBTYPE
     *
     * @mbggenerated
     */
    public BigDecimal getCorsubtype() {
        return corsubtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CORSUBTYPE
     *
     * @param corsubtype the value for CLT_CLT_INFO.CORSUBTYPE
     *
     * @mbggenerated
     */
    public void setCorsubtype(BigDecimal corsubtype) {
        this.corsubtype = corsubtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.OTHER
     *
     * @return the value of CLT_CLT_INFO.OTHER
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.OTHER
     *
     * @param other the value for CLT_CLT_INFO.OTHER
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.BANKNO
     *
     * @return the value of CLT_CLT_INFO.BANKNO
     *
     * @mbggenerated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.BANKNO
     *
     * @param bankno the value for CLT_CLT_INFO.BANKNO
     *
     * @mbggenerated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CREATOR
     *
     * @return the value of CLT_CLT_INFO.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CREATOR
     *
     * @param creator the value for CLT_CLT_INFO.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CREATETIME
     *
     * @return the value of CLT_CLT_INFO.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CREATETIME
     *
     * @param createtime the value for CLT_CLT_INFO.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.STAUTS
     *
     * @return the value of CLT_CLT_INFO.STAUTS
     *
     * @mbggenerated
     */
    public BigDecimal getStauts() {
        return stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.STAUTS
     *
     * @param stauts the value for CLT_CLT_INFO.STAUTS
     *
     * @mbggenerated
     */
    public void setStauts(BigDecimal stauts) {
        this.stauts = stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CAUSE
     *
     * @return the value of CLT_CLT_INFO.CAUSE
     *
     * @mbggenerated
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CAUSE
     *
     * @param cause the value for CLT_CLT_INFO.CAUSE
     *
     * @mbggenerated
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ENTERPRISESCALE
     *
     * @return the value of CLT_CLT_INFO.ENTERPRISESCALE
     *
     * @mbggenerated
     */
    public BigDecimal getEnterprisescale() {
        return enterprisescale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ENTERPRISESCALE
     *
     * @param enterprisescale the value for CLT_CLT_INFO.ENTERPRISESCALE
     *
     * @mbggenerated
     */
    public void setEnterprisescale(BigDecimal enterprisescale) {
        this.enterprisescale = enterprisescale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LICENSECODE
     *
     * @return the value of CLT_CLT_INFO.LICENSECODE
     *
     * @mbggenerated
     */
    public String getLicensecode() {
        return licensecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LICENSECODE
     *
     * @param licensecode the value for CLT_CLT_INFO.LICENSECODE
     *
     * @mbggenerated
     */
    public void setLicensecode(String licensecode) {
        this.licensecode = licensecode == null ? null : licensecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FINANCIALCODE
     *
     * @return the value of CLT_CLT_INFO.FINANCIALCODE
     *
     * @mbggenerated
     */
    public String getFinancialcode() {
        return financialcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FINANCIALCODE
     *
     * @param financialcode the value for CLT_CLT_INFO.FINANCIALCODE
     *
     * @mbggenerated
     */
    public void setFinancialcode(String financialcode) {
        this.financialcode = financialcode == null ? null : financialcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CLTSTATE
     *
     * @return the value of CLT_CLT_INFO.CLTSTATE
     *
     * @mbggenerated
     */
    public BigDecimal getCltstate() {
        return cltstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CLTSTATE
     *
     * @param cltstate the value for CLT_CLT_INFO.CLTSTATE
     *
     * @mbggenerated
     */
    public void setCltstate(BigDecimal cltstate) {
        this.cltstate = cltstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.EMAIL
     *
     * @return the value of CLT_CLT_INFO.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.EMAIL
     *
     * @param email the value for CLT_CLT_INFO.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FINANCIALCONTACT
     *
     * @return the value of CLT_CLT_INFO.FINANCIALCONTACT
     *
     * @mbggenerated
     */
    public String getFinancialcontact() {
        return financialcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FINANCIALCONTACT
     *
     * @param financialcontact the value for CLT_CLT_INFO.FINANCIALCONTACT
     *
     * @mbggenerated
     */
    public void setFinancialcontact(String financialcontact) {
        this.financialcontact = financialcontact == null ? null : financialcontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ENDDATE
     *
     * @return the value of CLT_CLT_INFO.ENDDATE
     *
     * @mbggenerated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ENDDATE
     *
     * @param enddate the value for CLT_CLT_INFO.ENDDATE
     *
     * @mbggenerated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.STOCKCODE
     *
     * @return the value of CLT_CLT_INFO.STOCKCODE
     *
     * @mbggenerated
     */
    public String getStockcode() {
        return stockcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.STOCKCODE
     *
     * @param stockcode the value for CLT_CLT_INFO.STOCKCODE
     *
     * @mbggenerated
     */
    public void setStockcode(String stockcode) {
        this.stockcode = stockcode == null ? null : stockcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.SITEAREA
     *
     * @return the value of CLT_CLT_INFO.SITEAREA
     *
     * @mbggenerated
     */
    public BigDecimal getSitearea() {
        return sitearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.SITEAREA
     *
     * @param sitearea the value for CLT_CLT_INFO.SITEAREA
     *
     * @mbggenerated
     */
    public void setSitearea(BigDecimal sitearea) {
        this.sitearea = sitearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.SITETITLE
     *
     * @return the value of CLT_CLT_INFO.SITETITLE
     *
     * @mbggenerated
     */
    public String getSitetitle() {
        return sitetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.SITETITLE
     *
     * @param sitetitle the value for CLT_CLT_INFO.SITETITLE
     *
     * @mbggenerated
     */
    public void setSitetitle(String sitetitle) {
        this.sitetitle = sitetitle == null ? null : sitetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.EMPLOYEESNUM
     *
     * @return the value of CLT_CLT_INFO.EMPLOYEESNUM
     *
     * @mbggenerated
     */
    public BigDecimal getEmployeesnum() {
        return employeesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.EMPLOYEESNUM
     *
     * @param employeesnum the value for CLT_CLT_INFO.EMPLOYEESNUM
     *
     * @mbggenerated
     */
    public void setEmployeesnum(BigDecimal employeesnum) {
        this.employeesnum = employeesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.TAXNUM
     *
     * @return the value of CLT_CLT_INFO.TAXNUM
     *
     * @mbggenerated
     */
    public String getTaxnum() {
        return taxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.TAXNUM
     *
     * @param taxnum the value for CLT_CLT_INFO.TAXNUM
     *
     * @mbggenerated
     */
    public void setTaxnum(String taxnum) {
        this.taxnum = taxnum == null ? null : taxnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LANDTAXNUM
     *
     * @return the value of CLT_CLT_INFO.LANDTAXNUM
     *
     * @mbggenerated
     */
    public String getLandtaxnum() {
        return landtaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LANDTAXNUM
     *
     * @param landtaxnum the value for CLT_CLT_INFO.LANDTAXNUM
     *
     * @mbggenerated
     */
    public void setLandtaxnum(String landtaxnum) {
        this.landtaxnum = landtaxnum == null ? null : landtaxnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PRODUCTSMAJOR
     *
     * @return the value of CLT_CLT_INFO.PRODUCTSMAJOR
     *
     * @mbggenerated
     */
    public String getProductsmajor() {
        return productsmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PRODUCTSMAJOR
     *
     * @param productsmajor the value for CLT_CLT_INFO.PRODUCTSMAJOR
     *
     * @mbggenerated
     */
    public void setProductsmajor(String productsmajor) {
        this.productsmajor = productsmajor == null ? null : productsmajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LISTEDPLACE
     *
     * @return the value of CLT_CLT_INFO.LISTEDPLACE
     *
     * @mbggenerated
     */
    public String getListedplace() {
        return listedplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LISTEDPLACE
     *
     * @param listedplace the value for CLT_CLT_INFO.LISTEDPLACE
     *
     * @mbggenerated
     */
    public void setListedplace(String listedplace) {
        this.listedplace = listedplace == null ? null : listedplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PROVINCE
     *
     * @return the value of CLT_CLT_INFO.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PROVINCE
     *
     * @param province the value for CLT_CLT_INFO.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CITY
     *
     * @return the value of CLT_CLT_INFO.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CITY
     *
     * @param city the value for CLT_CLT_INFO.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.DISTRICT
     *
     * @return the value of CLT_CLT_INFO.DISTRICT
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.DISTRICT
     *
     * @param district the value for CLT_CLT_INFO.DISTRICT
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.BORRNATURE
     *
     * @return the value of CLT_CLT_INFO.BORRNATURE
     *
     * @mbggenerated
     */
    public BigDecimal getBorrnature() {
        return borrnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.BORRNATURE
     *
     * @param borrnature the value for CLT_CLT_INFO.BORRNATURE
     *
     * @mbggenerated
     */
    public void setBorrnature(BigDecimal borrnature) {
        this.borrnature = borrnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.MECCODE
     *
     * @return the value of CLT_CLT_INFO.MECCODE
     *
     * @mbggenerated
     */
    public String getMeccode() {
        return meccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.MECCODE
     *
     * @param meccode the value for CLT_CLT_INFO.MECCODE
     *
     * @mbggenerated
     */
    public void setMeccode(String meccode) {
        this.meccode = meccode == null ? null : meccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PROJECTNAME
     *
     * @return the value of CLT_CLT_INFO.PROJECTNAME
     *
     * @mbggenerated
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PROJECTNAME
     *
     * @param projectname the value for CLT_CLT_INFO.PROJECTNAME
     *
     * @mbggenerated
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.COMPANTYATTRIBUTE
     *
     * @return the value of CLT_CLT_INFO.COMPANTYATTRIBUTE
     *
     * @mbggenerated
     */
    public BigDecimal getCompantyattribute() {
        return compantyattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.COMPANTYATTRIBUTE
     *
     * @param compantyattribute the value for CLT_CLT_INFO.COMPANTYATTRIBUTE
     *
     * @mbggenerated
     */
    public void setCompantyattribute(BigDecimal compantyattribute) {
        this.compantyattribute = compantyattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REGIONTEXT
     *
     * @return the value of CLT_CLT_INFO.REGIONTEXT
     *
     * @mbggenerated
     */
    public String getRegiontext() {
        return regiontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REGIONTEXT
     *
     * @param regiontext the value for CLT_CLT_INFO.REGIONTEXT
     *
     * @mbggenerated
     */
    public void setRegiontext(String regiontext) {
        this.regiontext = regiontext == null ? null : regiontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.LEFTFIG_N3
     *
     * @return the value of CLT_CLT_INFO.LEFTFIG_N3
     *
     * @mbggenerated
     */
    public BigDecimal getLeftfigN3() {
        return leftfigN3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.LEFTFIG_N3
     *
     * @param leftfigN3 the value for CLT_CLT_INFO.LEFTFIG_N3
     *
     * @mbggenerated
     */
    public void setLeftfigN3(BigDecimal leftfigN3) {
        this.leftfigN3 = leftfigN3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.RIGHTFIG_N3
     *
     * @return the value of CLT_CLT_INFO.RIGHTFIG_N3
     *
     * @mbggenerated
     */
    public BigDecimal getRightfigN3() {
        return rightfigN3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.RIGHTFIG_N3
     *
     * @param rightfigN3 the value for CLT_CLT_INFO.RIGHTFIG_N3
     *
     * @mbggenerated
     */
    public void setRightfigN3(BigDecimal rightfigN3) {
        this.rightfigN3 = rightfigN3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.DEPT_TYPE
     *
     * @return the value of CLT_CLT_INFO.DEPT_TYPE
     *
     * @mbggenerated
     */
    public String getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.DEPT_TYPE
     *
     * @param deptType the value for CLT_CLT_INFO.DEPT_TYPE
     *
     * @mbggenerated
     */
    public void setDeptType(String deptType) {
        this.deptType = deptType == null ? null : deptType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORG_PARENT_ID
     *
     * @return the value of CLT_CLT_INFO.ORG_PARENT_ID
     *
     * @mbggenerated
     */
    public String getOrgParentId() {
        return orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORG_PARENT_ID
     *
     * @param orgParentId the value for CLT_CLT_INFO.ORG_PARENT_ID
     *
     * @mbggenerated
     */
    public void setOrgParentId(String orgParentId) {
        this.orgParentId = orgParentId == null ? null : orgParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ROLEGROUPID
     *
     * @return the value of CLT_CLT_INFO.ROLEGROUPID
     *
     * @mbggenerated
     */
    public BigDecimal getRolegroupid() {
        return rolegroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ROLEGROUPID
     *
     * @param rolegroupid the value for CLT_CLT_INFO.ROLEGROUPID
     *
     * @mbggenerated
     */
    public void setRolegroupid(BigDecimal rolegroupid) {
        this.rolegroupid = rolegroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FINA_PRINCIPAL
     *
     * @return the value of CLT_CLT_INFO.FINA_PRINCIPAL
     *
     * @mbggenerated
     */
    public String getFinaPrincipal() {
        return finaPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FINA_PRINCIPAL
     *
     * @param finaPrincipal the value for CLT_CLT_INFO.FINA_PRINCIPAL
     *
     * @mbggenerated
     */
    public void setFinaPrincipal(String finaPrincipal) {
        this.finaPrincipal = finaPrincipal == null ? null : finaPrincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PRIMARY_ACC_NO
     *
     * @return the value of CLT_CLT_INFO.PRIMARY_ACC_NO
     *
     * @mbggenerated
     */
    public String getPrimaryAccNo() {
        return primaryAccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PRIMARY_ACC_NO
     *
     * @param primaryAccNo the value for CLT_CLT_INFO.PRIMARY_ACC_NO
     *
     * @mbggenerated
     */
    public void setPrimaryAccNo(String primaryAccNo) {
        this.primaryAccNo = primaryAccNo == null ? null : primaryAccNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CONTACT_PERSON
     *
     * @return the value of CLT_CLT_INFO.CONTACT_PERSON
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CONTACT_PERSON
     *
     * @param contactPerson the value for CLT_CLT_INFO.CONTACT_PERSON
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REMARK_
     *
     * @return the value of CLT_CLT_INFO.REMARK_
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REMARK_
     *
     * @param remark the value for CLT_CLT_INFO.REMARK_
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.SYNC_FLAG
     *
     * @return the value of CLT_CLT_INFO.SYNC_FLAG
     *
     * @mbggenerated
     */
    public BigDecimal getSyncFlag() {
        return syncFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.SYNC_FLAG
     *
     * @param syncFlag the value for CLT_CLT_INFO.SYNC_FLAG
     *
     * @mbggenerated
     */
    public void setSyncFlag(BigDecimal syncFlag) {
        this.syncFlag = syncFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.SYNC_VERSION
     *
     * @return the value of CLT_CLT_INFO.SYNC_VERSION
     *
     * @mbggenerated
     */
    public BigDecimal getSyncVersion() {
        return syncVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.SYNC_VERSION
     *
     * @param syncVersion the value for CLT_CLT_INFO.SYNC_VERSION
     *
     * @mbggenerated
     */
    public void setSyncVersion(BigDecimal syncVersion) {
        this.syncVersion = syncVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.AUTH_BY_USER_FLAG
     *
     * @return the value of CLT_CLT_INFO.AUTH_BY_USER_FLAG
     *
     * @mbggenerated
     */
    public BigDecimal getAuthByUserFlag() {
        return authByUserFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.AUTH_BY_USER_FLAG
     *
     * @param authByUserFlag the value for CLT_CLT_INFO.AUTH_BY_USER_FLAG
     *
     * @mbggenerated
     */
    public void setAuthByUserFlag(BigDecimal authByUserFlag) {
        this.authByUserFlag = authByUserFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.AGENCY_NO
     *
     * @return the value of CLT_CLT_INFO.AGENCY_NO
     *
     * @mbggenerated
     */
    public String getAgencyNo() {
        return agencyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.AGENCY_NO
     *
     * @param agencyNo the value for CLT_CLT_INFO.AGENCY_NO
     *
     * @mbggenerated
     */
    public void setAgencyNo(String agencyNo) {
        this.agencyNo = agencyNo == null ? null : agencyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.STATUS
     *
     * @return the value of CLT_CLT_INFO.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.STATUS
     *
     * @param status the value for CLT_CLT_INFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORG_ORDER
     *
     * @return the value of CLT_CLT_INFO.ORG_ORDER
     *
     * @mbggenerated
     */
    public BigDecimal getOrgOrder() {
        return orgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORG_ORDER
     *
     * @param orgOrder the value for CLT_CLT_INFO.ORG_ORDER
     *
     * @mbggenerated
     */
    public void setOrgOrder(BigDecimal orgOrder) {
        this.orgOrder = orgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORG_LEVEL
     *
     * @return the value of CLT_CLT_INFO.ORG_LEVEL
     *
     * @mbggenerated
     */
    public BigDecimal getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORG_LEVEL
     *
     * @param orgLevel the value for CLT_CLT_INFO.ORG_LEVEL
     *
     * @mbggenerated
     */
    public void setOrgLevel(BigDecimal orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.MOBILE_PHONE
     *
     * @return the value of CLT_CLT_INFO.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.MOBILE_PHONE
     *
     * @param mobilePhone the value for CLT_CLT_INFO.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORGCLASSID
     *
     * @return the value of CLT_CLT_INFO.ORGCLASSID
     *
     * @mbggenerated
     */
    public Long getOrgclassid() {
        return orgclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORGCLASSID
     *
     * @param orgclassid the value for CLT_CLT_INFO.ORGCLASSID
     *
     * @mbggenerated
     */
    public void setOrgclassid(Long orgclassid) {
        this.orgclassid = orgclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.PARENT_ID
     *
     * @return the value of CLT_CLT_INFO.PARENT_ID
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.PARENT_ID
     *
     * @param parentId the value for CLT_CLT_INFO.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.INSTICREDITCODE
     *
     * @return the value of CLT_CLT_INFO.INSTICREDITCODE
     *
     * @mbggenerated
     */
    public String getInsticreditcode() {
        return insticreditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.INSTICREDITCODE
     *
     * @param insticreditcode the value for CLT_CLT_INFO.INSTICREDITCODE
     *
     * @mbggenerated
     */
    public void setInsticreditcode(String insticreditcode) {
        this.insticreditcode = insticreditcode == null ? null : insticreditcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REGNUMCODE
     *
     * @return the value of CLT_CLT_INFO.REGNUMCODE
     *
     * @mbggenerated
     */
    public String getRegnumcode() {
        return regnumcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REGNUMCODE
     *
     * @param regnumcode the value for CLT_CLT_INFO.REGNUMCODE
     *
     * @mbggenerated
     */
    public void setRegnumcode(String regnumcode) {
        this.regnumcode = regnumcode == null ? null : regnumcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.APPRONUM
     *
     * @return the value of CLT_CLT_INFO.APPRONUM
     *
     * @mbggenerated
     */
    public String getAppronum() {
        return appronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.APPRONUM
     *
     * @param appronum the value for CLT_CLT_INFO.APPRONUM
     *
     * @mbggenerated
     */
    public void setAppronum(String appronum) {
        this.appronum = appronum == null ? null : appronum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORGTYPEDETAIL
     *
     * @return the value of CLT_CLT_INFO.ORGTYPEDETAIL
     *
     * @mbggenerated
     */
    public String getOrgtypedetail() {
        return orgtypedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORGTYPEDETAIL
     *
     * @param orgtypedetail the value for CLT_CLT_INFO.ORGTYPEDETAIL
     *
     * @mbggenerated
     */
    public void setOrgtypedetail(String orgtypedetail) {
        this.orgtypedetail = orgtypedetail == null ? null : orgtypedetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.BCOMMADD
     *
     * @return the value of CLT_CLT_INFO.BCOMMADD
     *
     * @mbggenerated
     */
    public String getBcommadd() {
        return bcommadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.BCOMMADD
     *
     * @param bcommadd the value for CLT_CLT_INFO.BCOMMADD
     *
     * @mbggenerated
     */
    public void setBcommadd(String bcommadd) {
        this.bcommadd = bcommadd == null ? null : bcommadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.CLTTYPE
     *
     * @return the value of CLT_CLT_INFO.CLTTYPE
     *
     * @mbggenerated
     */
    public String getClttype() {
        return clttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.CLTTYPE
     *
     * @param clttype the value for CLT_CLT_INFO.CLTTYPE
     *
     * @mbggenerated
     */
    public void setClttype(String clttype) {
        this.clttype = clttype == null ? null : clttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.ORGTYPE
     *
     * @return the value of CLT_CLT_INFO.ORGTYPE
     *
     * @mbggenerated
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.ORGTYPE
     *
     * @param orgtype the value for CLT_CLT_INFO.ORGTYPE
     *
     * @mbggenerated
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.MANAGEBANKCODE
     *
     * @return the value of CLT_CLT_INFO.MANAGEBANKCODE
     *
     * @mbggenerated
     */
    public String getManagebankcode() {
        return managebankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.MANAGEBANKCODE
     *
     * @param managebankcode the value for CLT_CLT_INFO.MANAGEBANKCODE
     *
     * @mbggenerated
     */
    public void setManagebankcode(String managebankcode) {
        this.managebankcode = managebankcode == null ? null : managebankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.FORTDRTFG
     *
     * @return the value of CLT_CLT_INFO.FORTDRTFG
     *
     * @mbggenerated
     */
    public String getFortdrtfg() {
        return fortdrtfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.FORTDRTFG
     *
     * @param fortdrtfg the value for CLT_CLT_INFO.FORTDRTFG
     *
     * @mbggenerated
     */
    public void setFortdrtfg(String fortdrtfg) {
        this.fortdrtfg = fortdrtfg == null ? null : fortdrtfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLT_CLT_INFO.REGCODE
     *
     * @return the value of CLT_CLT_INFO.REGCODE
     *
     * @mbggenerated
     */
    public String getRegcode() {
        return regcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLT_CLT_INFO.REGCODE
     *
     * @param regcode the value for CLT_CLT_INFO.REGCODE
     *
     * @mbggenerated
     */
    public void setRegcode(String regcode) {
        this.regcode = regcode == null ? null : regcode.trim();
    }
}