package entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WstCashsweepAcntdataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public WstCashsweepAcntdataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCltnoIsNull() {
            addCriterion("CLTNO is null");
            return (Criteria) this;
        }

        public Criteria andCltnoIsNotNull() {
            addCriterion("CLTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCltnoEqualTo(String value) {
            addCriterion("CLTNO =", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotEqualTo(String value) {
            addCriterion("CLTNO <>", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoGreaterThan(String value) {
            addCriterion("CLTNO >", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoGreaterThanOrEqualTo(String value) {
            addCriterion("CLTNO >=", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLessThan(String value) {
            addCriterion("CLTNO <", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLessThanOrEqualTo(String value) {
            addCriterion("CLTNO <=", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLike(String value) {
            addCriterion("CLTNO like", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotLike(String value) {
            addCriterion("CLTNO not like", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoIn(List<String> values) {
            addCriterion("CLTNO in", values, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotIn(List<String> values) {
            addCriterion("CLTNO not in", values, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoBetween(String value1, String value2) {
            addCriterion("CLTNO between", value1, value2, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotBetween(String value1, String value2) {
            addCriterion("CLTNO not between", value1, value2, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnameIsNull() {
            addCriterion("CLTNAME is null");
            return (Criteria) this;
        }

        public Criteria andCltnameIsNotNull() {
            addCriterion("CLTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCltnameEqualTo(String value) {
            addCriterion("CLTNAME =", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameNotEqualTo(String value) {
            addCriterion("CLTNAME <>", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameGreaterThan(String value) {
            addCriterion("CLTNAME >", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameGreaterThanOrEqualTo(String value) {
            addCriterion("CLTNAME >=", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameLessThan(String value) {
            addCriterion("CLTNAME <", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameLessThanOrEqualTo(String value) {
            addCriterion("CLTNAME <=", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameLike(String value) {
            addCriterion("CLTNAME like", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameNotLike(String value) {
            addCriterion("CLTNAME not like", value, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameIn(List<String> values) {
            addCriterion("CLTNAME in", values, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameNotIn(List<String> values) {
            addCriterion("CLTNAME not in", values, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameBetween(String value1, String value2) {
            addCriterion("CLTNAME between", value1, value2, "cltname");
            return (Criteria) this;
        }

        public Criteria andCltnameNotBetween(String value1, String value2) {
            addCriterion("CLTNAME not between", value1, value2, "cltname");
            return (Criteria) this;
        }

        public Criteria andBanknoIsNull() {
            addCriterion("BANKNO is null");
            return (Criteria) this;
        }

        public Criteria andBanknoIsNotNull() {
            addCriterion("BANKNO is not null");
            return (Criteria) this;
        }

        public Criteria andBanknoEqualTo(String value) {
            addCriterion("BANKNO =", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoNotEqualTo(String value) {
            addCriterion("BANKNO <>", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoGreaterThan(String value) {
            addCriterion("BANKNO >", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNO >=", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoLessThan(String value) {
            addCriterion("BANKNO <", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoLessThanOrEqualTo(String value) {
            addCriterion("BANKNO <=", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoLike(String value) {
            addCriterion("BANKNO like", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoNotLike(String value) {
            addCriterion("BANKNO not like", value, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoIn(List<String> values) {
            addCriterion("BANKNO in", values, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoNotIn(List<String> values) {
            addCriterion("BANKNO not in", values, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoBetween(String value1, String value2) {
            addCriterion("BANKNO between", value1, value2, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknoNotBetween(String value1, String value2) {
            addCriterion("BANKNO not between", value1, value2, "bankno");
            return (Criteria) this;
        }

        public Criteria andBanknameIsNull() {
            addCriterion("BANKNAME is null");
            return (Criteria) this;
        }

        public Criteria andBanknameIsNotNull() {
            addCriterion("BANKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBanknameEqualTo(String value) {
            addCriterion("BANKNAME =", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotEqualTo(String value) {
            addCriterion("BANKNAME <>", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameGreaterThan(String value) {
            addCriterion("BANKNAME >", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameGreaterThanOrEqualTo(String value) {
            addCriterion("BANKNAME >=", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLessThan(String value) {
            addCriterion("BANKNAME <", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLessThanOrEqualTo(String value) {
            addCriterion("BANKNAME <=", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLike(String value) {
            addCriterion("BANKNAME like", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotLike(String value) {
            addCriterion("BANKNAME not like", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameIn(List<String> values) {
            addCriterion("BANKNAME in", values, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotIn(List<String> values) {
            addCriterion("BANKNAME not in", values, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameBetween(String value1, String value2) {
            addCriterion("BANKNAME between", value1, value2, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotBetween(String value1, String value2) {
            addCriterion("BANKNAME not between", value1, value2, "bankname");
            return (Criteria) this;
        }

        public Criteria andAcntnoIsNull() {
            addCriterion("ACNTNO is null");
            return (Criteria) this;
        }

        public Criteria andAcntnoIsNotNull() {
            addCriterion("ACNTNO is not null");
            return (Criteria) this;
        }

        public Criteria andAcntnoEqualTo(String value) {
            addCriterion("ACNTNO =", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoNotEqualTo(String value) {
            addCriterion("ACNTNO <>", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoGreaterThan(String value) {
            addCriterion("ACNTNO >", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACNTNO >=", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoLessThan(String value) {
            addCriterion("ACNTNO <", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoLessThanOrEqualTo(String value) {
            addCriterion("ACNTNO <=", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoLike(String value) {
            addCriterion("ACNTNO like", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoNotLike(String value) {
            addCriterion("ACNTNO not like", value, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoIn(List<String> values) {
            addCriterion("ACNTNO in", values, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoNotIn(List<String> values) {
            addCriterion("ACNTNO not in", values, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoBetween(String value1, String value2) {
            addCriterion("ACNTNO between", value1, value2, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcntnoNotBetween(String value1, String value2) {
            addCriterion("ACNTNO not between", value1, value2, "acntno");
            return (Criteria) this;
        }

        public Criteria andAcnttypeIsNull() {
            addCriterion("ACNTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andAcnttypeIsNotNull() {
            addCriterion("ACNTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAcnttypeEqualTo(String value) {
            addCriterion("ACNTTYPE =", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeNotEqualTo(String value) {
            addCriterion("ACNTTYPE <>", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeGreaterThan(String value) {
            addCriterion("ACNTTYPE >", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACNTTYPE >=", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeLessThan(String value) {
            addCriterion("ACNTTYPE <", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeLessThanOrEqualTo(String value) {
            addCriterion("ACNTTYPE <=", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeLike(String value) {
            addCriterion("ACNTTYPE like", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeNotLike(String value) {
            addCriterion("ACNTTYPE not like", value, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeIn(List<String> values) {
            addCriterion("ACNTTYPE in", values, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeNotIn(List<String> values) {
            addCriterion("ACNTTYPE not in", values, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeBetween(String value1, String value2) {
            addCriterion("ACNTTYPE between", value1, value2, "acnttype");
            return (Criteria) this;
        }

        public Criteria andAcnttypeNotBetween(String value1, String value2) {
            addCriterion("ACNTTYPE not between", value1, value2, "acnttype");
            return (Criteria) this;
        }

        public Criteria andActdateIsNull() {
            addCriterion("ACTDATE is null");
            return (Criteria) this;
        }

        public Criteria andActdateIsNotNull() {
            addCriterion("ACTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andActdateEqualTo(Date value) {
            addCriterion("ACTDATE =", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateNotEqualTo(Date value) {
            addCriterion("ACTDATE <>", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateGreaterThan(Date value) {
            addCriterion("ACTDATE >", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTDATE >=", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateLessThan(Date value) {
            addCriterion("ACTDATE <", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateLessThanOrEqualTo(Date value) {
            addCriterion("ACTDATE <=", value, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateIn(List<Date> values) {
            addCriterion("ACTDATE in", values, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateNotIn(List<Date> values) {
            addCriterion("ACTDATE not in", values, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateBetween(Date value1, Date value2) {
            addCriterion("ACTDATE between", value1, value2, "actdate");
            return (Criteria) this;
        }

        public Criteria andActdateNotBetween(Date value1, Date value2) {
            addCriterion("ACTDATE not between", value1, value2, "actdate");
            return (Criteria) this;
        }

        public Criteria andInamountIsNull() {
            addCriterion("INAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andInamountIsNotNull() {
            addCriterion("INAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andInamountEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT =", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT <>", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountGreaterThan(BigDecimal value) {
            addCriterion("INAMOUNT >", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT >=", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountLessThan(BigDecimal value) {
            addCriterion("INAMOUNT <", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT <=", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountIn(List<BigDecimal> values) {
            addCriterion("INAMOUNT in", values, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotIn(List<BigDecimal> values) {
            addCriterion("INAMOUNT not in", values, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAMOUNT between", value1, value2, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAMOUNT not between", value1, value2, "inamount");
            return (Criteria) this;
        }

        public Criteria andOutamountIsNull() {
            addCriterion("OUTAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andOutamountIsNotNull() {
            addCriterion("OUTAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOutamountEqualTo(BigDecimal value) {
            addCriterion("OUTAMOUNT =", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountNotEqualTo(BigDecimal value) {
            addCriterion("OUTAMOUNT <>", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountGreaterThan(BigDecimal value) {
            addCriterion("OUTAMOUNT >", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OUTAMOUNT >=", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountLessThan(BigDecimal value) {
            addCriterion("OUTAMOUNT <", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OUTAMOUNT <=", value, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountIn(List<BigDecimal> values) {
            addCriterion("OUTAMOUNT in", values, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountNotIn(List<BigDecimal> values) {
            addCriterion("OUTAMOUNT not in", values, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OUTAMOUNT between", value1, value2, "outamount");
            return (Criteria) this;
        }

        public Criteria andOutamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OUTAMOUNT not between", value1, value2, "outamount");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("BALANCE is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("BALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("BALANCE =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("BALANCE <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("BALANCE >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("BALANCE <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("BALANCE in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("BALANCE not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("CREATORID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("CREATORID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("CREATORID =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("CREATORID <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("CREATORID >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORID >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("CREATORID <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("CREATORID <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("CREATORID like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("CREATORID not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("CREATORID in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("CREATORID not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("CREATORID between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("CREATORID not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBhstateIsNull() {
            addCriterion("BHSTATE is null");
            return (Criteria) this;
        }

        public Criteria andBhstateIsNotNull() {
            addCriterion("BHSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andBhstateEqualTo(String value) {
            addCriterion("BHSTATE =", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateNotEqualTo(String value) {
            addCriterion("BHSTATE <>", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateGreaterThan(String value) {
            addCriterion("BHSTATE >", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateGreaterThanOrEqualTo(String value) {
            addCriterion("BHSTATE >=", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateLessThan(String value) {
            addCriterion("BHSTATE <", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateLessThanOrEqualTo(String value) {
            addCriterion("BHSTATE <=", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateLike(String value) {
            addCriterion("BHSTATE like", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateNotLike(String value) {
            addCriterion("BHSTATE not like", value, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateIn(List<String> values) {
            addCriterion("BHSTATE in", values, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateNotIn(List<String> values) {
            addCriterion("BHSTATE not in", values, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateBetween(String value1, String value2) {
            addCriterion("BHSTATE between", value1, value2, "bhstate");
            return (Criteria) this;
        }

        public Criteria andBhstateNotBetween(String value1, String value2) {
            addCriterion("BHSTATE not between", value1, value2, "bhstate");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("REASON is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("REASON is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("REASON =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("REASON <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("REASON >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("REASON >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("REASON <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("REASON <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("REASON like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("REASON not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("REASON in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("REASON not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("REASON between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("REASON not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNull() {
            addCriterion("LASTUPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNotNull() {
            addCriterion("LASTUPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeEqualTo(Date value) {
            addCriterion("LASTUPDATETIME =", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotEqualTo(Date value) {
            addCriterion("LASTUPDATETIME <>", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThan(Date value) {
            addCriterion("LASTUPDATETIME >", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATETIME >=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThan(Date value) {
            addCriterion("LASTUPDATETIME <", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATETIME <=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIn(List<Date> values) {
            addCriterion("LASTUPDATETIME in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotIn(List<Date> values) {
            addCriterion("LASTUPDATETIME not in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATETIME between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATETIME not between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andCashtypeIsNull() {
            addCriterion("CASHTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCashtypeIsNotNull() {
            addCriterion("CASHTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCashtypeEqualTo(String value) {
            addCriterion("CASHTYPE =", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeNotEqualTo(String value) {
            addCriterion("CASHTYPE <>", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeGreaterThan(String value) {
            addCriterion("CASHTYPE >", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeGreaterThanOrEqualTo(String value) {
            addCriterion("CASHTYPE >=", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeLessThan(String value) {
            addCriterion("CASHTYPE <", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeLessThanOrEqualTo(String value) {
            addCriterion("CASHTYPE <=", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeLike(String value) {
            addCriterion("CASHTYPE like", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeNotLike(String value) {
            addCriterion("CASHTYPE not like", value, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeIn(List<String> values) {
            addCriterion("CASHTYPE in", values, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeNotIn(List<String> values) {
            addCriterion("CASHTYPE not in", values, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeBetween(String value1, String value2) {
            addCriterion("CASHTYPE between", value1, value2, "cashtype");
            return (Criteria) this;
        }

        public Criteria andCashtypeNotBetween(String value1, String value2) {
            addCriterion("CASHTYPE not between", value1, value2, "cashtype");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceIsNull() {
            addCriterion("TOTALBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceIsNotNull() {
            addCriterion("TOTALBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceEqualTo(BigDecimal value) {
            addCriterion("TOTALBALANCE =", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceNotEqualTo(BigDecimal value) {
            addCriterion("TOTALBALANCE <>", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceGreaterThan(BigDecimal value) {
            addCriterion("TOTALBALANCE >", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALBALANCE >=", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceLessThan(BigDecimal value) {
            addCriterion("TOTALBALANCE <", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALBALANCE <=", value, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceIn(List<BigDecimal> values) {
            addCriterion("TOTALBALANCE in", values, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceNotIn(List<BigDecimal> values) {
            addCriterion("TOTALBALANCE not in", values, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALBALANCE between", value1, value2, "totalbalance");
            return (Criteria) this;
        }

        public Criteria andTotalbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALBALANCE not between", value1, value2, "totalbalance");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP_ACNTDATA
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}