package entity;

import java.math.BigDecimal;
import java.util.Date;

public class WstCashsweepAcntdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CLTNO
     *
     * @mbggenerated
     */
    private String cltno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CLTNAME
     *
     * @mbggenerated
     */
    private String cltname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.BANKNO
     *
     * @mbggenerated
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.BANKNAME
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.ACNTNO
     *
     * @mbggenerated
     */
    private String acntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.ACNTTYPE
     *
     * @mbggenerated
     */
    private String acnttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.ACTDATE
     *
     * @mbggenerated
     */
    private Date actdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.INAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal inamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.OUTAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal outamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CREATORID
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.BHSTATE
     *
     * @mbggenerated
     */
    private String bhstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.LASTUPDATETIME
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.CASHTYPE
     *
     * @mbggenerated
     */
    private String cashtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP_ACNTDATA.TOTALBALANCE
     *
     * @mbggenerated
     */
    private BigDecimal totalbalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.ID
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.ID
     *
     * @param id the value for WST_CASHSWEEP_ACNTDATA.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CLTNO
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CLTNO
     *
     * @mbggenerated
     */
    public String getCltno() {
        return cltno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CLTNO
     *
     * @param cltno the value for WST_CASHSWEEP_ACNTDATA.CLTNO
     *
     * @mbggenerated
     */
    public void setCltno(String cltno) {
        this.cltno = cltno == null ? null : cltno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CLTNAME
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CLTNAME
     *
     * @mbggenerated
     */
    public String getCltname() {
        return cltname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CLTNAME
     *
     * @param cltname the value for WST_CASHSWEEP_ACNTDATA.CLTNAME
     *
     * @mbggenerated
     */
    public void setCltname(String cltname) {
        this.cltname = cltname == null ? null : cltname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.BANKNO
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.BANKNO
     *
     * @mbggenerated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.BANKNO
     *
     * @param bankno the value for WST_CASHSWEEP_ACNTDATA.BANKNO
     *
     * @mbggenerated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.BANKNAME
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.BANKNAME
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.BANKNAME
     *
     * @param bankname the value for WST_CASHSWEEP_ACNTDATA.BANKNAME
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.ACNTNO
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.ACNTNO
     *
     * @mbggenerated
     */
    public String getAcntno() {
        return acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.ACNTNO
     *
     * @param acntno the value for WST_CASHSWEEP_ACNTDATA.ACNTNO
     *
     * @mbggenerated
     */
    public void setAcntno(String acntno) {
        this.acntno = acntno == null ? null : acntno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.ACNTTYPE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.ACNTTYPE
     *
     * @mbggenerated
     */
    public String getAcnttype() {
        return acnttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.ACNTTYPE
     *
     * @param acnttype the value for WST_CASHSWEEP_ACNTDATA.ACNTTYPE
     *
     * @mbggenerated
     */
    public void setAcnttype(String acnttype) {
        this.acnttype = acnttype == null ? null : acnttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.ACTDATE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.ACTDATE
     *
     * @mbggenerated
     */
    public Date getActdate() {
        return actdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.ACTDATE
     *
     * @param actdate the value for WST_CASHSWEEP_ACNTDATA.ACTDATE
     *
     * @mbggenerated
     */
    public void setActdate(Date actdate) {

        this.actdate = actdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.INAMOUNT
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.INAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getInamount() {
        return inamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.INAMOUNT
     *
     * @param inamount the value for WST_CASHSWEEP_ACNTDATA.INAMOUNT
     *
     * @mbggenerated
     */
    public void setInamount(BigDecimal inamount) {
        this.inamount = inamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.OUTAMOUNT
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.OUTAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getOutamount() {
        return outamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.OUTAMOUNT
     *
     * @param outamount the value for WST_CASHSWEEP_ACNTDATA.OUTAMOUNT
     *
     * @mbggenerated
     */
    public void setOutamount(BigDecimal outamount) {
        this.outamount = outamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.BALANCE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.BALANCE
     *
     * @param balance the value for WST_CASHSWEEP_ACNTDATA.BALANCE
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CREATORID
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CREATORID
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CREATORID
     *
     * @param creatorid the value for WST_CASHSWEEP_ACNTDATA.CREATORID
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CREATOR
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CREATOR
     *
     * @param creator the value for WST_CASHSWEEP_ACNTDATA.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.STATE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.STATE
     *
     * @mbggenerated
     */
    public String getState() {



   return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.STATE
     *
     * @param state the value for WST_CASHSWEEP_ACNTDATA.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        if (state.equals("0")){
            this.state="已导入，待提交";
        }
        else if (state.equals("1")){
            this.state="已提交，待复核";
        }
         else if (state.equals("2")){
            this.state="已复核，待审批";
        }
        else {this.state="已审批";}

//        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.BHSTATE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.BHSTATE
     *
     * @mbggenerated
     */
    public String getBhstate() {
        return bhstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.BHSTATE
     *
     * @param bhstate the value for WST_CASHSWEEP_ACNTDATA.BHSTATE
     *
     * @mbggenerated
     */
    public void setBhstate(String bhstate) {
        this.bhstate = bhstate == null ? null : bhstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.REASON
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.REASON
     *
     * @param reason the value for WST_CASHSWEEP_ACNTDATA.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CREATETIME
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CREATETIME
     *
     * @param createtime the value for WST_CASHSWEEP_ACNTDATA.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.LASTUPDATETIME
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.LASTUPDATETIME
     *
     * @param lastupdatetime the value for WST_CASHSWEEP_ACNTDATA.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.CASHTYPE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.CASHTYPE
     *
     * @mbggenerated
     */
    public String getCashtype() {
        return cashtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.CASHTYPE
     *
     * @param cashtype the value for WST_CASHSWEEP_ACNTDATA.CASHTYPE
     *
     * @mbggenerated
     */
    public void setCashtype(String cashtype) {
        this.cashtype = cashtype == null ? null : cashtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP_ACNTDATA.TOTALBALANCE
     *
     * @return the value of WST_CASHSWEEP_ACNTDATA.TOTALBALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getTotalbalance() {
        return totalbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP_ACNTDATA.TOTALBALANCE
     *
     * @param totalbalance the value for WST_CASHSWEEP_ACNTDATA.TOTALBALANCE
     *
     * @mbggenerated
     */
    public void setTotalbalance(BigDecimal totalbalance) {
        this.totalbalance = totalbalance;
    }
}