package entity;

import java.math.BigDecimal;
import java.util.Date;

public class WstCashsweep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CLTNO
     *
     * @mbggenerated
     */
    private String cltno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.RE_YEAR
     *
     * @mbggenerated
     */
    private String re_year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.RE_MONTH
     *
     * @mbggenerated
     */
    private String re_month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CURRENCYNO
     *
     * @mbggenerated
     */
    private String currencyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.ENTRYTIME
     *
     * @mbggenerated
     */
    private Date entrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CREATEUSERID
     *
     * @mbggenerated
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.LASTUPDATETIME
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    private BigDecimal currencymoneybalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CANSWEEPBALANCE
     *
     * @mbggenerated
     */
    private BigDecimal cansweepbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal cannotsweeptotalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.STOCKAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal stockamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.BILLPLEDGEAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal billpledgeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.GUARANTEEAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal guaranteeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CREDITAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal creditamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.SUBJETAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal subjetamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.OTHERCANNOTSWEEPAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal othercannotsweepamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.BEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal beforemonthamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CASHSWEEPRATE
     *
     * @mbggenerated
     */
    private String cashsweeprate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CANCASHSWEEPRATE
     *
     * @mbggenerated
     */
    private String cancashsweeprate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.DESSTATE
     *
     * @mbggenerated
     */
    private String desstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.YEAR_MONTH
     *
     * @mbggenerated
     */
    private String year_month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.ALREADYAUTHAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal alreadyauthamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.NOAUTHAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal noauthamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    private String cashsweepratemean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.CANCASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    private String cancashsweepratemean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.TOTALCURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    private BigDecimal totalcurrencymoneybalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.TOTALCANSWEEPBALANCE
     *
     * @mbggenerated
     */
    private BigDecimal totalcansweepbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.TOTALCANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal totalcannotsweeptotalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.TOTALBEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal totalbeforemonthamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WST_CASHSWEEP.TOTALDAY
     *
     * @mbggenerated
     */
    private BigDecimal totalday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.ID
     *
     * @return the value of WST_CASHSWEEP.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.ID
     *
     * @param id the value for WST_CASHSWEEP.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CLTNO
     *
     * @return the value of WST_CASHSWEEP.CLTNO
     *
     * @mbggenerated
     */
    public String getCltno() {
        return cltno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CLTNO
     *
     * @param cltno the value for WST_CASHSWEEP.CLTNO
     *
     * @mbggenerated
     */
    public void setCltno(String cltno) {
        this.cltno = cltno == null ? null : cltno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.RE_YEAR
     *
     * @return the value of WST_CASHSWEEP.RE_YEAR
     *
     * @mbggenerated
     */
    public String getRe_year() {
        return re_year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.RE_YEAR
     *
     * @param re_year the value for WST_CASHSWEEP.RE_YEAR
     *
     * @mbggenerated
     */
    public void setRe_year(String re_year) {
        this.re_year = re_year == null ? null : re_year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.RE_MONTH
     *
     * @return the value of WST_CASHSWEEP.RE_MONTH
     *
     * @mbggenerated
     */
    public String getRe_month() {
        return re_month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.RE_MONTH
     *
     * @param re_month the value for WST_CASHSWEEP.RE_MONTH
     *
     * @mbggenerated
     */
    public void setRe_month(String re_month) {
        this.re_month = re_month == null ? null : re_month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CURRENCYNO
     *
     * @return the value of WST_CASHSWEEP.CURRENCYNO
     *
     * @mbggenerated
     */
    public String getCurrencyno() {
        return currencyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CURRENCYNO
     *
     * @param currencyno the value for WST_CASHSWEEP.CURRENCYNO
     *
     * @mbggenerated
     */
    public void setCurrencyno(String currencyno) {
        this.currencyno = currencyno == null ? null : currencyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.ENTRYTIME
     *
     * @return the value of WST_CASHSWEEP.ENTRYTIME
     *
     * @mbggenerated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.ENTRYTIME
     *
     * @param entrytime the value for WST_CASHSWEEP.ENTRYTIME
     *
     * @mbggenerated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CREATETIME
     *
     * @return the value of WST_CASHSWEEP.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CREATETIME
     *
     * @param createtime the value for WST_CASHSWEEP.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CREATEUSERID
     *
     * @return the value of WST_CASHSWEEP.CREATEUSERID
     *
     * @mbggenerated
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CREATEUSERID
     *
     * @param createuserid the value for WST_CASHSWEEP.CREATEUSERID
     *
     * @mbggenerated
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.LASTUPDATETIME
     *
     * @return the value of WST_CASHSWEEP.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.LASTUPDATETIME
     *
     * @param lastupdatetime the value for WST_CASHSWEEP.LASTUPDATETIME
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CURRENCYMONEYBALANCE
     *
     * @return the value of WST_CASHSWEEP.CURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getCurrencymoneybalance() {
        return currencymoneybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CURRENCYMONEYBALANCE
     *
     * @param currencymoneybalance the value for WST_CASHSWEEP.CURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    public void setCurrencymoneybalance(BigDecimal currencymoneybalance) {
        this.currencymoneybalance = currencymoneybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CANSWEEPBALANCE
     *
     * @return the value of WST_CASHSWEEP.CANSWEEPBALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getCansweepbalance() {
        return cansweepbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CANSWEEPBALANCE
     *
     * @param cansweepbalance the value for WST_CASHSWEEP.CANSWEEPBALANCE
     *
     * @mbggenerated
     */
    public void setCansweepbalance(BigDecimal cansweepbalance) {
        this.cansweepbalance = cansweepbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CANNOTSWEEPTOTALAMOUNT
     *
     * @return the value of WST_CASHSWEEP.CANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getCannotsweeptotalamount() {
        return cannotsweeptotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CANNOTSWEEPTOTALAMOUNT
     *
     * @param cannotsweeptotalamount the value for WST_CASHSWEEP.CANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    public void setCannotsweeptotalamount(BigDecimal cannotsweeptotalamount) {
        this.cannotsweeptotalamount = cannotsweeptotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.STOCKAMOUNT
     *
     * @return the value of WST_CASHSWEEP.STOCKAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getStockamount() {
        return stockamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.STOCKAMOUNT
     *
     * @param stockamount the value for WST_CASHSWEEP.STOCKAMOUNT
     *
     * @mbggenerated
     */
    public void setStockamount(BigDecimal stockamount) {
        this.stockamount = stockamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.BILLPLEDGEAMOUNT
     *
     * @return the value of WST_CASHSWEEP.BILLPLEDGEAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getBillpledgeamount() {
        return billpledgeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.BILLPLEDGEAMOUNT
     *
     * @param billpledgeamount the value for WST_CASHSWEEP.BILLPLEDGEAMOUNT
     *
     * @mbggenerated
     */
    public void setBillpledgeamount(BigDecimal billpledgeamount) {
        this.billpledgeamount = billpledgeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.GUARANTEEAMOUNT
     *
     * @return the value of WST_CASHSWEEP.GUARANTEEAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getGuaranteeamount() {
        return guaranteeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.GUARANTEEAMOUNT
     *
     * @param guaranteeamount the value for WST_CASHSWEEP.GUARANTEEAMOUNT
     *
     * @mbggenerated
     */
    public void setGuaranteeamount(BigDecimal guaranteeamount) {
        this.guaranteeamount = guaranteeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CREDITAMOUNT
     *
     * @return the value of WST_CASHSWEEP.CREDITAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getCreditamount() {
        return creditamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CREDITAMOUNT
     *
     * @param creditamount the value for WST_CASHSWEEP.CREDITAMOUNT
     *
     * @mbggenerated
     */
    public void setCreditamount(BigDecimal creditamount) {
        this.creditamount = creditamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.SUBJETAMOUNT
     *
     * @return the value of WST_CASHSWEEP.SUBJETAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getSubjetamount() {
        return subjetamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.SUBJETAMOUNT
     *
     * @param subjetamount the value for WST_CASHSWEEP.SUBJETAMOUNT
     *
     * @mbggenerated
     */
    public void setSubjetamount(BigDecimal subjetamount) {
        this.subjetamount = subjetamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.OTHERCANNOTSWEEPAMOUNT
     *
     * @return the value of WST_CASHSWEEP.OTHERCANNOTSWEEPAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getOthercannotsweepamount() {
        return othercannotsweepamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.OTHERCANNOTSWEEPAMOUNT
     *
     * @param othercannotsweepamount the value for WST_CASHSWEEP.OTHERCANNOTSWEEPAMOUNT
     *
     * @mbggenerated
     */
    public void setOthercannotsweepamount(BigDecimal othercannotsweepamount) {
        this.othercannotsweepamount = othercannotsweepamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.BEFOREMONTHAMOUNT
     *
     * @return the value of WST_CASHSWEEP.BEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getBeforemonthamount() {
        return beforemonthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.BEFOREMONTHAMOUNT
     *
     * @param beforemonthamount the value for WST_CASHSWEEP.BEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    public void setBeforemonthamount(BigDecimal beforemonthamount) {
        this.beforemonthamount = beforemonthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CASHSWEEPRATE
     *
     * @return the value of WST_CASHSWEEP.CASHSWEEPRATE
     *
     * @mbggenerated
     */
    public String getCashsweeprate() {
        return cashsweeprate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CASHSWEEPRATE
     *
     * @param cashsweeprate the value for WST_CASHSWEEP.CASHSWEEPRATE
     *
     * @mbggenerated
     */
    public void setCashsweeprate(String cashsweeprate) {
        this.cashsweeprate = cashsweeprate == null ? null : cashsweeprate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CANCASHSWEEPRATE
     *
     * @return the value of WST_CASHSWEEP.CANCASHSWEEPRATE
     *
     * @mbggenerated
     */
    public String getCancashsweeprate() {
        return cancashsweeprate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CANCASHSWEEPRATE
     *
     * @param cancashsweeprate the value for WST_CASHSWEEP.CANCASHSWEEPRATE
     *
     * @mbggenerated
     */
    public void setCancashsweeprate(String cancashsweeprate) {
        this.cancashsweeprate = cancashsweeprate == null ? null : cancashsweeprate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.STATE
     *
     * @return the value of WST_CASHSWEEP.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.STATE
     *
     * @param state the value for WST_CASHSWEEP.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.DESSTATE
     *
     * @return the value of WST_CASHSWEEP.DESSTATE
     *
     * @mbggenerated
     */
    public String getDesstate() {
        return desstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.DESSTATE
     *
     * @param desstate the value for WST_CASHSWEEP.DESSTATE
     *
     * @mbggenerated
     */
    public void setDesstate(String desstate) {
        this.desstate = desstate == null ? null : desstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.REASON
     *
     * @return the value of WST_CASHSWEEP.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.REASON
     *
     * @param reason the value for WST_CASHSWEEP.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.YEAR_MONTH
     *
     * @return the value of WST_CASHSWEEP.YEAR_MONTH
     *
     * @mbggenerated
     */
    public String getYear_month() {
        return year_month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.YEAR_MONTH
     *
     * @param yearMonth the value for WST_CASHSWEEP.YEAR_MONTH
     *
     * @mbggenerated
     */
    public void setYear_month(String yearMonth) {
        this.year_month = year_month == null ? null : year_month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.ALREADYAUTHAMOUNT
     *
     * @return the value of WST_CASHSWEEP.ALREADYAUTHAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAlreadyauthamount() {
        return alreadyauthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.ALREADYAUTHAMOUNT
     *
     * @param alreadyauthamount the value for WST_CASHSWEEP.ALREADYAUTHAMOUNT
     *
     * @mbggenerated
     */
    public void setAlreadyauthamount(BigDecimal alreadyauthamount) {
        this.alreadyauthamount = alreadyauthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.NOAUTHAMOUNT
     *
     * @return the value of WST_CASHSWEEP.NOAUTHAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getNoauthamount() {
        return noauthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.NOAUTHAMOUNT
     *
     * @param noauthamount the value for WST_CASHSWEEP.NOAUTHAMOUNT
     *
     * @mbggenerated
     */
    public void setNoauthamount(BigDecimal noauthamount) {
        this.noauthamount = noauthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CASHSWEEPRATEMEAN
     *
     * @return the value of WST_CASHSWEEP.CASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    public String getCashsweepratemean() {
        return cashsweepratemean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CASHSWEEPRATEMEAN
     *
     * @param cashsweepratemean the value for WST_CASHSWEEP.CASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    public void setCashsweepratemean(String cashsweepratemean) {
        this.cashsweepratemean = cashsweepratemean == null ? null : cashsweepratemean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.CANCASHSWEEPRATEMEAN
     *
     * @return the value of WST_CASHSWEEP.CANCASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    public String getCancashsweepratemean() {
        return cancashsweepratemean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.CANCASHSWEEPRATEMEAN
     *
     * @param cancashsweepratemean the value for WST_CASHSWEEP.CANCASHSWEEPRATEMEAN
     *
     * @mbggenerated
     */
    public void setCancashsweepratemean(String cancashsweepratemean) {
        this.cancashsweepratemean = cancashsweepratemean == null ? null : cancashsweepratemean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.TOTALCURRENCYMONEYBALANCE
     *
     * @return the value of WST_CASHSWEEP.TOTALCURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getTotalcurrencymoneybalance() {
        return totalcurrencymoneybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.TOTALCURRENCYMONEYBALANCE
     *
     * @param totalcurrencymoneybalance the value for WST_CASHSWEEP.TOTALCURRENCYMONEYBALANCE
     *
     * @mbggenerated
     */
    public void setTotalcurrencymoneybalance(BigDecimal totalcurrencymoneybalance) {
        this.totalcurrencymoneybalance = totalcurrencymoneybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.TOTALCANSWEEPBALANCE
     *
     * @return the value of WST_CASHSWEEP.TOTALCANSWEEPBALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getTotalcansweepbalance() {
        return totalcansweepbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.TOTALCANSWEEPBALANCE
     *
     * @param totalcansweepbalance the value for WST_CASHSWEEP.TOTALCANSWEEPBALANCE
     *
     * @mbggenerated
     */
    public void setTotalcansweepbalance(BigDecimal totalcansweepbalance) {
        this.totalcansweepbalance = totalcansweepbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.TOTALCANNOTSWEEPTOTALAMOUNT
     *
     * @return the value of WST_CASHSWEEP.TOTALCANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTotalcannotsweeptotalamount() {
        return totalcannotsweeptotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.TOTALCANNOTSWEEPTOTALAMOUNT
     *
     * @param totalcannotsweeptotalamount the value for WST_CASHSWEEP.TOTALCANNOTSWEEPTOTALAMOUNT
     *
     * @mbggenerated
     */
    public void setTotalcannotsweeptotalamount(BigDecimal totalcannotsweeptotalamount) {
        this.totalcannotsweeptotalamount = totalcannotsweeptotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.TOTALBEFOREMONTHAMOUNT
     *
     * @return the value of WST_CASHSWEEP.TOTALBEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTotalbeforemonthamount() {
        return totalbeforemonthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.TOTALBEFOREMONTHAMOUNT
     *
     * @param totalbeforemonthamount the value for WST_CASHSWEEP.TOTALBEFOREMONTHAMOUNT
     *
     * @mbggenerated
     */
    public void setTotalbeforemonthamount(BigDecimal totalbeforemonthamount) {
        this.totalbeforemonthamount = totalbeforemonthamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WST_CASHSWEEP.TOTALDAY
     *
     * @return the value of WST_CASHSWEEP.TOTALDAY
     *
     * @mbggenerated
     */
    public BigDecimal getTotalday() {
        return totalday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WST_CASHSWEEP.TOTALDAY
     *
     * @param totalday the value for WST_CASHSWEEP.TOTALDAY
     *
     * @mbggenerated
     */
    public void setTotalday(BigDecimal totalday) {
        this.totalday = totalday;
    }

    public String getCltname() {
        return cltname;
    }

    public void setCltname(String cltname) {
        this.cltname = cltname;
    }

    private  String cltname ;


}