package entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WstCashsweepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public WstCashsweepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCltnoIsNull() {
            addCriterion("CLTNO is null");
            return (Criteria) this;
        }

        public Criteria andCltnoIsNotNull() {
            addCriterion("CLTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCltnoEqualTo(String value) {
            addCriterion("CLTNO =", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotEqualTo(String value) {
            addCriterion("CLTNO <>", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoGreaterThan(String value) {
            addCriterion("CLTNO >", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoGreaterThanOrEqualTo(String value) {
            addCriterion("CLTNO >=", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLessThan(String value) {
            addCriterion("CLTNO <", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLessThanOrEqualTo(String value) {
            addCriterion("CLTNO <=", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoLike(String value) {
            addCriterion("CLTNO like", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotLike(String value) {
            addCriterion("CLTNO not like", value, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoIn(List<String> values) {
            addCriterion("CLTNO in", values, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotIn(List<String> values) {
            addCriterion("CLTNO not in", values, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoBetween(String value1, String value2) {
            addCriterion("CLTNO between", value1, value2, "cltno");
            return (Criteria) this;
        }

        public Criteria andCltnoNotBetween(String value1, String value2) {
            addCriterion("CLTNO not between", value1, value2, "cltno");
            return (Criteria) this;
        }

        public Criteria andReYearIsNull() {
            addCriterion("RE_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andReYearIsNotNull() {
            addCriterion("RE_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andReYearEqualTo(String value) {
            addCriterion("RE_YEAR =", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearNotEqualTo(String value) {
            addCriterion("RE_YEAR <>", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearGreaterThan(String value) {
            addCriterion("RE_YEAR >", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearGreaterThanOrEqualTo(String value) {
            addCriterion("RE_YEAR >=", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearLessThan(String value) {
            addCriterion("RE_YEAR <", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearLessThanOrEqualTo(String value) {
            addCriterion("RE_YEAR <=", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearLike(String value) {
            addCriterion("RE_YEAR like", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearNotLike(String value) {
            addCriterion("RE_YEAR not like", value, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearIn(List<String> values) {
            addCriterion("RE_YEAR in", values, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearNotIn(List<String> values) {
            addCriterion("RE_YEAR not in", values, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearBetween(String value1, String value2) {
            addCriterion("RE_YEAR between", value1, value2, "reYear");
            return (Criteria) this;
        }

        public Criteria andReYearNotBetween(String value1, String value2) {
            addCriterion("RE_YEAR not between", value1, value2, "reYear");
            return (Criteria) this;
        }

        public Criteria andReMonthIsNull() {
            addCriterion("RE_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andReMonthIsNotNull() {
            addCriterion("RE_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andReMonthEqualTo(String value) {
            addCriterion("RE_MONTH =", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthNotEqualTo(String value) {
            addCriterion("RE_MONTH <>", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthGreaterThan(String value) {
            addCriterion("RE_MONTH >", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthGreaterThanOrEqualTo(String value) {
            addCriterion("RE_MONTH >=", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthLessThan(String value) {
            addCriterion("RE_MONTH <", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthLessThanOrEqualTo(String value) {
            addCriterion("RE_MONTH <=", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthLike(String value) {
            addCriterion("RE_MONTH like", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthNotLike(String value) {
            addCriterion("RE_MONTH not like", value, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthIn(List<String> values) {
            addCriterion("RE_MONTH in", values, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthNotIn(List<String> values) {
            addCriterion("RE_MONTH not in", values, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthBetween(String value1, String value2) {
            addCriterion("RE_MONTH between", value1, value2, "reMonth");
            return (Criteria) this;
        }

        public Criteria andReMonthNotBetween(String value1, String value2) {
            addCriterion("RE_MONTH not between", value1, value2, "reMonth");
            return (Criteria) this;
        }

        public Criteria andCurrencynoIsNull() {
            addCriterion("CURRENCYNO is null");
            return (Criteria) this;
        }

        public Criteria andCurrencynoIsNotNull() {
            addCriterion("CURRENCYNO is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencynoEqualTo(String value) {
            addCriterion("CURRENCYNO =", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoNotEqualTo(String value) {
            addCriterion("CURRENCYNO <>", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoGreaterThan(String value) {
            addCriterion("CURRENCYNO >", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCYNO >=", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoLessThan(String value) {
            addCriterion("CURRENCYNO <", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoLessThanOrEqualTo(String value) {
            addCriterion("CURRENCYNO <=", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoLike(String value) {
            addCriterion("CURRENCYNO like", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoNotLike(String value) {
            addCriterion("CURRENCYNO not like", value, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoIn(List<String> values) {
            addCriterion("CURRENCYNO in", values, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoNotIn(List<String> values) {
            addCriterion("CURRENCYNO not in", values, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoBetween(String value1, String value2) {
            addCriterion("CURRENCYNO between", value1, value2, "currencyno");
            return (Criteria) this;
        }

        public Criteria andCurrencynoNotBetween(String value1, String value2) {
            addCriterion("CURRENCYNO not between", value1, value2, "currencyno");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNull() {
            addCriterion("ENTRYTIME is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNotNull() {
            addCriterion("ENTRYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeEqualTo(Date value) {
            addCriterion("ENTRYTIME =", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotEqualTo(Date value) {
            addCriterion("ENTRYTIME <>", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThan(Date value) {
            addCriterion("ENTRYTIME >", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ENTRYTIME >=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThan(Date value) {
            addCriterion("ENTRYTIME <", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThanOrEqualTo(Date value) {
            addCriterion("ENTRYTIME <=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIn(List<Date> values) {
            addCriterion("ENTRYTIME in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotIn(List<Date> values) {
            addCriterion("ENTRYTIME not in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeBetween(Date value1, Date value2) {
            addCriterion("ENTRYTIME between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotBetween(Date value1, Date value2) {
            addCriterion("ENTRYTIME not between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreateuseridIsNull() {
            addCriterion("CREATEUSERID is null");
            return (Criteria) this;
        }

        public Criteria andCreateuseridIsNotNull() {
            addCriterion("CREATEUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuseridEqualTo(String value) {
            addCriterion("CREATEUSERID =", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridNotEqualTo(String value) {
            addCriterion("CREATEUSERID <>", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridGreaterThan(String value) {
            addCriterion("CREATEUSERID >", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID >=", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridLessThan(String value) {
            addCriterion("CREATEUSERID <", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID <=", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridLike(String value) {
            addCriterion("CREATEUSERID like", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridNotLike(String value) {
            addCriterion("CREATEUSERID not like", value, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridIn(List<String> values) {
            addCriterion("CREATEUSERID in", values, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridNotIn(List<String> values) {
            addCriterion("CREATEUSERID not in", values, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridBetween(String value1, String value2) {
            addCriterion("CREATEUSERID between", value1, value2, "createuserid");
            return (Criteria) this;
        }

        public Criteria andCreateuseridNotBetween(String value1, String value2) {
            addCriterion("CREATEUSERID not between", value1, value2, "createuserid");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNull() {
            addCriterion("LASTUPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNotNull() {
            addCriterion("LASTUPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeEqualTo(Date value) {
            addCriterion("LASTUPDATETIME =", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotEqualTo(Date value) {
            addCriterion("LASTUPDATETIME <>", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThan(Date value) {
            addCriterion("LASTUPDATETIME >", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATETIME >=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThan(Date value) {
            addCriterion("LASTUPDATETIME <", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATETIME <=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIn(List<Date> values) {
            addCriterion("LASTUPDATETIME in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotIn(List<Date> values) {
            addCriterion("LASTUPDATETIME not in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATETIME between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATETIME not between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceIsNull() {
            addCriterion("CURRENCYMONEYBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceIsNotNull() {
            addCriterion("CURRENCYMONEYBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceEqualTo(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE =", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceNotEqualTo(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE <>", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceGreaterThan(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE >", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE >=", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceLessThan(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE <", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRENCYMONEYBALANCE <=", value, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceIn(List<BigDecimal> values) {
            addCriterion("CURRENCYMONEYBALANCE in", values, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceNotIn(List<BigDecimal> values) {
            addCriterion("CURRENCYMONEYBALANCE not in", values, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRENCYMONEYBALANCE between", value1, value2, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCurrencymoneybalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRENCYMONEYBALANCE not between", value1, value2, "currencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceIsNull() {
            addCriterion("CANSWEEPBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceIsNotNull() {
            addCriterion("CANSWEEPBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceEqualTo(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE =", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceNotEqualTo(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE <>", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceGreaterThan(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE >", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE >=", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceLessThan(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE <", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CANSWEEPBALANCE <=", value, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceIn(List<BigDecimal> values) {
            addCriterion("CANSWEEPBALANCE in", values, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceNotIn(List<BigDecimal> values) {
            addCriterion("CANSWEEPBALANCE not in", values, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CANSWEEPBALANCE between", value1, value2, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCansweepbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CANSWEEPBALANCE not between", value1, value2, "cansweepbalance");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountIsNull() {
            addCriterion("CANNOTSWEEPTOTALAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountIsNotNull() {
            addCriterion("CANNOTSWEEPTOTALAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountEqualTo(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT =", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountNotEqualTo(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT <>", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountGreaterThan(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT >", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT >=", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountLessThan(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT <", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT <=", value, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountIn(List<BigDecimal> values) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT in", values, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountNotIn(List<BigDecimal> values) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT not in", values, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT between", value1, value2, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andCannotsweeptotalamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CANNOTSWEEPTOTALAMOUNT not between", value1, value2, "cannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andStockamountIsNull() {
            addCriterion("STOCKAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andStockamountIsNotNull() {
            addCriterion("STOCKAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andStockamountEqualTo(BigDecimal value) {
            addCriterion("STOCKAMOUNT =", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountNotEqualTo(BigDecimal value) {
            addCriterion("STOCKAMOUNT <>", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountGreaterThan(BigDecimal value) {
            addCriterion("STOCKAMOUNT >", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STOCKAMOUNT >=", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountLessThan(BigDecimal value) {
            addCriterion("STOCKAMOUNT <", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STOCKAMOUNT <=", value, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountIn(List<BigDecimal> values) {
            addCriterion("STOCKAMOUNT in", values, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountNotIn(List<BigDecimal> values) {
            addCriterion("STOCKAMOUNT not in", values, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STOCKAMOUNT between", value1, value2, "stockamount");
            return (Criteria) this;
        }

        public Criteria andStockamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STOCKAMOUNT not between", value1, value2, "stockamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountIsNull() {
            addCriterion("BILLPLEDGEAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountIsNotNull() {
            addCriterion("BILLPLEDGEAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountEqualTo(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT =", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountNotEqualTo(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT <>", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountGreaterThan(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT >", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT >=", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountLessThan(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT <", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BILLPLEDGEAMOUNT <=", value, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountIn(List<BigDecimal> values) {
            addCriterion("BILLPLEDGEAMOUNT in", values, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountNotIn(List<BigDecimal> values) {
            addCriterion("BILLPLEDGEAMOUNT not in", values, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILLPLEDGEAMOUNT between", value1, value2, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andBillpledgeamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BILLPLEDGEAMOUNT not between", value1, value2, "billpledgeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountIsNull() {
            addCriterion("GUARANTEEAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountIsNotNull() {
            addCriterion("GUARANTEEAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountEqualTo(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT =", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountNotEqualTo(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT <>", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountGreaterThan(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT >", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT >=", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountLessThan(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT <", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GUARANTEEAMOUNT <=", value, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountIn(List<BigDecimal> values) {
            addCriterion("GUARANTEEAMOUNT in", values, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountNotIn(List<BigDecimal> values) {
            addCriterion("GUARANTEEAMOUNT not in", values, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GUARANTEEAMOUNT between", value1, value2, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andGuaranteeamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GUARANTEEAMOUNT not between", value1, value2, "guaranteeamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountIsNull() {
            addCriterion("CREDITAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCreditamountIsNotNull() {
            addCriterion("CREDITAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCreditamountEqualTo(BigDecimal value) {
            addCriterion("CREDITAMOUNT =", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountNotEqualTo(BigDecimal value) {
            addCriterion("CREDITAMOUNT <>", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountGreaterThan(BigDecimal value) {
            addCriterion("CREDITAMOUNT >", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREDITAMOUNT >=", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountLessThan(BigDecimal value) {
            addCriterion("CREDITAMOUNT <", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREDITAMOUNT <=", value, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountIn(List<BigDecimal> values) {
            addCriterion("CREDITAMOUNT in", values, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountNotIn(List<BigDecimal> values) {
            addCriterion("CREDITAMOUNT not in", values, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREDITAMOUNT between", value1, value2, "creditamount");
            return (Criteria) this;
        }

        public Criteria andCreditamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREDITAMOUNT not between", value1, value2, "creditamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountIsNull() {
            addCriterion("SUBJETAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSubjetamountIsNotNull() {
            addCriterion("SUBJETAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjetamountEqualTo(BigDecimal value) {
            addCriterion("SUBJETAMOUNT =", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountNotEqualTo(BigDecimal value) {
            addCriterion("SUBJETAMOUNT <>", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountGreaterThan(BigDecimal value) {
            addCriterion("SUBJETAMOUNT >", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBJETAMOUNT >=", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountLessThan(BigDecimal value) {
            addCriterion("SUBJETAMOUNT <", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBJETAMOUNT <=", value, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountIn(List<BigDecimal> values) {
            addCriterion("SUBJETAMOUNT in", values, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountNotIn(List<BigDecimal> values) {
            addCriterion("SUBJETAMOUNT not in", values, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBJETAMOUNT between", value1, value2, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andSubjetamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBJETAMOUNT not between", value1, value2, "subjetamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountIsNull() {
            addCriterion("OTHERCANNOTSWEEPAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountIsNotNull() {
            addCriterion("OTHERCANNOTSWEEPAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountEqualTo(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT =", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountNotEqualTo(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT <>", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountGreaterThan(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT >", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT >=", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountLessThan(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT <", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT <=", value, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountIn(List<BigDecimal> values) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT in", values, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountNotIn(List<BigDecimal> values) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT not in", values, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT between", value1, value2, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andOthercannotsweepamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OTHERCANNOTSWEEPAMOUNT not between", value1, value2, "othercannotsweepamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountIsNull() {
            addCriterion("BEFOREMONTHAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountIsNotNull() {
            addCriterion("BEFOREMONTHAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountEqualTo(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT =", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountNotEqualTo(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT <>", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountGreaterThan(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT >", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT >=", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountLessThan(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT <", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BEFOREMONTHAMOUNT <=", value, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountIn(List<BigDecimal> values) {
            addCriterion("BEFOREMONTHAMOUNT in", values, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountNotIn(List<BigDecimal> values) {
            addCriterion("BEFOREMONTHAMOUNT not in", values, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BEFOREMONTHAMOUNT between", value1, value2, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andBeforemonthamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BEFOREMONTHAMOUNT not between", value1, value2, "beforemonthamount");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateIsNull() {
            addCriterion("CASHSWEEPRATE is null");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateIsNotNull() {
            addCriterion("CASHSWEEPRATE is not null");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateEqualTo(String value) {
            addCriterion("CASHSWEEPRATE =", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateNotEqualTo(String value) {
            addCriterion("CASHSWEEPRATE <>", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateGreaterThan(String value) {
            addCriterion("CASHSWEEPRATE >", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateGreaterThanOrEqualTo(String value) {
            addCriterion("CASHSWEEPRATE >=", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateLessThan(String value) {
            addCriterion("CASHSWEEPRATE <", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateLessThanOrEqualTo(String value) {
            addCriterion("CASHSWEEPRATE <=", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateLike(String value) {
            addCriterion("CASHSWEEPRATE like", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateNotLike(String value) {
            addCriterion("CASHSWEEPRATE not like", value, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateIn(List<String> values) {
            addCriterion("CASHSWEEPRATE in", values, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateNotIn(List<String> values) {
            addCriterion("CASHSWEEPRATE not in", values, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateBetween(String value1, String value2) {
            addCriterion("CASHSWEEPRATE between", value1, value2, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCashsweeprateNotBetween(String value1, String value2) {
            addCriterion("CASHSWEEPRATE not between", value1, value2, "cashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateIsNull() {
            addCriterion("CANCASHSWEEPRATE is null");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateIsNotNull() {
            addCriterion("CANCASHSWEEPRATE is not null");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATE =", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateNotEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATE <>", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateGreaterThan(String value) {
            addCriterion("CANCASHSWEEPRATE >", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateGreaterThanOrEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATE >=", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateLessThan(String value) {
            addCriterion("CANCASHSWEEPRATE <", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateLessThanOrEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATE <=", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateLike(String value) {
            addCriterion("CANCASHSWEEPRATE like", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateNotLike(String value) {
            addCriterion("CANCASHSWEEPRATE not like", value, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateIn(List<String> values) {
            addCriterion("CANCASHSWEEPRATE in", values, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateNotIn(List<String> values) {
            addCriterion("CANCASHSWEEPRATE not in", values, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateBetween(String value1, String value2) {
            addCriterion("CANCASHSWEEPRATE between", value1, value2, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andCancashsweeprateNotBetween(String value1, String value2) {
            addCriterion("CANCASHSWEEPRATE not between", value1, value2, "cancashsweeprate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDesstateIsNull() {
            addCriterion("DESSTATE is null");
            return (Criteria) this;
        }

        public Criteria andDesstateIsNotNull() {
            addCriterion("DESSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andDesstateEqualTo(String value) {
            addCriterion("DESSTATE =", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateNotEqualTo(String value) {
            addCriterion("DESSTATE <>", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateGreaterThan(String value) {
            addCriterion("DESSTATE >", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateGreaterThanOrEqualTo(String value) {
            addCriterion("DESSTATE >=", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateLessThan(String value) {
            addCriterion("DESSTATE <", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateLessThanOrEqualTo(String value) {
            addCriterion("DESSTATE <=", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateLike(String value) {
            addCriterion("DESSTATE like", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateNotLike(String value) {
            addCriterion("DESSTATE not like", value, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateIn(List<String> values) {
            addCriterion("DESSTATE in", values, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateNotIn(List<String> values) {
            addCriterion("DESSTATE not in", values, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateBetween(String value1, String value2) {
            addCriterion("DESSTATE between", value1, value2, "desstate");
            return (Criteria) this;
        }

        public Criteria andDesstateNotBetween(String value1, String value2) {
            addCriterion("DESSTATE not between", value1, value2, "desstate");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("REASON is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("REASON is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("REASON =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("REASON <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("REASON >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("REASON >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("REASON <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("REASON <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("REASON like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("REASON not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("REASON in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("REASON not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("REASON between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("REASON not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andYearMonthIsNull() {
            addCriterion("YEAR_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andYearMonthIsNotNull() {
            addCriterion("YEAR_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andYearMonthEqualTo(String value) {
            addCriterion("YEAR_MONTH =", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthNotEqualTo(String value) {
            addCriterion("YEAR_MONTH <>", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthGreaterThan(String value) {
            addCriterion("YEAR_MONTH >", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthGreaterThanOrEqualTo(String value) {
            addCriterion("YEAR_MONTH >=", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthLessThan(String value) {
            addCriterion("YEAR_MONTH <", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthLessThanOrEqualTo(String value) {
            addCriterion("YEAR_MONTH <=", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthLike(String value) {
            addCriterion("YEAR_MONTH like", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthNotLike(String value) {
            addCriterion("YEAR_MONTH not like", value, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthIn(List<String> values) {
            addCriterion("YEAR_MONTH in", values, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthNotIn(List<String> values) {
            addCriterion("YEAR_MONTH not in", values, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthBetween(String value1, String value2) {
            addCriterion("YEAR_MONTH between", value1, value2, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andYearMonthNotBetween(String value1, String value2) {
            addCriterion("YEAR_MONTH not between", value1, value2, "yearMonth");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountIsNull() {
            addCriterion("ALREADYAUTHAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountIsNotNull() {
            addCriterion("ALREADYAUTHAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountEqualTo(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT =", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountNotEqualTo(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT <>", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountGreaterThan(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT >", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT >=", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountLessThan(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT <", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ALREADYAUTHAMOUNT <=", value, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountIn(List<BigDecimal> values) {
            addCriterion("ALREADYAUTHAMOUNT in", values, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountNotIn(List<BigDecimal> values) {
            addCriterion("ALREADYAUTHAMOUNT not in", values, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ALREADYAUTHAMOUNT between", value1, value2, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andAlreadyauthamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ALREADYAUTHAMOUNT not between", value1, value2, "alreadyauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountIsNull() {
            addCriterion("NOAUTHAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andNoauthamountIsNotNull() {
            addCriterion("NOAUTHAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andNoauthamountEqualTo(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT =", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountNotEqualTo(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT <>", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountGreaterThan(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT >", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT >=", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountLessThan(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT <", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NOAUTHAMOUNT <=", value, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountIn(List<BigDecimal> values) {
            addCriterion("NOAUTHAMOUNT in", values, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountNotIn(List<BigDecimal> values) {
            addCriterion("NOAUTHAMOUNT not in", values, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NOAUTHAMOUNT between", value1, value2, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andNoauthamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NOAUTHAMOUNT not between", value1, value2, "noauthamount");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanIsNull() {
            addCriterion("CASHSWEEPRATEMEAN is null");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanIsNotNull() {
            addCriterion("CASHSWEEPRATEMEAN is not null");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanEqualTo(String value) {
            addCriterion("CASHSWEEPRATEMEAN =", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanNotEqualTo(String value) {
            addCriterion("CASHSWEEPRATEMEAN <>", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanGreaterThan(String value) {
            addCriterion("CASHSWEEPRATEMEAN >", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanGreaterThanOrEqualTo(String value) {
            addCriterion("CASHSWEEPRATEMEAN >=", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanLessThan(String value) {
            addCriterion("CASHSWEEPRATEMEAN <", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanLessThanOrEqualTo(String value) {
            addCriterion("CASHSWEEPRATEMEAN <=", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanLike(String value) {
            addCriterion("CASHSWEEPRATEMEAN like", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanNotLike(String value) {
            addCriterion("CASHSWEEPRATEMEAN not like", value, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanIn(List<String> values) {
            addCriterion("CASHSWEEPRATEMEAN in", values, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanNotIn(List<String> values) {
            addCriterion("CASHSWEEPRATEMEAN not in", values, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanBetween(String value1, String value2) {
            addCriterion("CASHSWEEPRATEMEAN between", value1, value2, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCashsweepratemeanNotBetween(String value1, String value2) {
            addCriterion("CASHSWEEPRATEMEAN not between", value1, value2, "cashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanIsNull() {
            addCriterion("CANCASHSWEEPRATEMEAN is null");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanIsNotNull() {
            addCriterion("CANCASHSWEEPRATEMEAN is not null");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN =", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanNotEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN <>", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanGreaterThan(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN >", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanGreaterThanOrEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN >=", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanLessThan(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN <", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanLessThanOrEqualTo(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN <=", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanLike(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN like", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanNotLike(String value) {
            addCriterion("CANCASHSWEEPRATEMEAN not like", value, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanIn(List<String> values) {
            addCriterion("CANCASHSWEEPRATEMEAN in", values, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanNotIn(List<String> values) {
            addCriterion("CANCASHSWEEPRATEMEAN not in", values, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanBetween(String value1, String value2) {
            addCriterion("CANCASHSWEEPRATEMEAN between", value1, value2, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andCancashsweepratemeanNotBetween(String value1, String value2) {
            addCriterion("CANCASHSWEEPRATEMEAN not between", value1, value2, "cancashsweepratemean");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceIsNull() {
            addCriterion("TOTALCURRENCYMONEYBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceIsNotNull() {
            addCriterion("TOTALCURRENCYMONEYBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceEqualTo(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE =", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE <>", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceGreaterThan(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE >", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE >=", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceLessThan(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE <", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCURRENCYMONEYBALANCE <=", value, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceIn(List<BigDecimal> values) {
            addCriterion("TOTALCURRENCYMONEYBALANCE in", values, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCURRENCYMONEYBALANCE not in", values, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCURRENCYMONEYBALANCE between", value1, value2, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcurrencymoneybalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCURRENCYMONEYBALANCE not between", value1, value2, "totalcurrencymoneybalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceIsNull() {
            addCriterion("TOTALCANSWEEPBALANCE is null");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceIsNotNull() {
            addCriterion("TOTALCANSWEEPBALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceEqualTo(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE =", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE <>", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceGreaterThan(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE >", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE >=", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceLessThan(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE <", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCANSWEEPBALANCE <=", value, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceIn(List<BigDecimal> values) {
            addCriterion("TOTALCANSWEEPBALANCE in", values, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCANSWEEPBALANCE not in", values, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCANSWEEPBALANCE between", value1, value2, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcansweepbalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCANSWEEPBALANCE not between", value1, value2, "totalcansweepbalance");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountIsNull() {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountIsNotNull() {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountEqualTo(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT =", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT <>", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountGreaterThan(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT >", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT >=", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountLessThan(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT <", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT <=", value, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountIn(List<BigDecimal> values) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT in", values, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT not in", values, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT between", value1, value2, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalcannotsweeptotalamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCANNOTSWEEPTOTALAMOUNT not between", value1, value2, "totalcannotsweeptotalamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountIsNull() {
            addCriterion("TOTALBEFOREMONTHAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountIsNotNull() {
            addCriterion("TOTALBEFOREMONTHAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountEqualTo(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT =", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountNotEqualTo(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT <>", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountGreaterThan(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT >", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT >=", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountLessThan(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT <", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALBEFOREMONTHAMOUNT <=", value, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountIn(List<BigDecimal> values) {
            addCriterion("TOTALBEFOREMONTHAMOUNT in", values, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountNotIn(List<BigDecimal> values) {
            addCriterion("TOTALBEFOREMONTHAMOUNT not in", values, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALBEFOREMONTHAMOUNT between", value1, value2, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotalbeforemonthamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALBEFOREMONTHAMOUNT not between", value1, value2, "totalbeforemonthamount");
            return (Criteria) this;
        }

        public Criteria andTotaldayIsNull() {
            addCriterion("TOTALDAY is null");
            return (Criteria) this;
        }

        public Criteria andTotaldayIsNotNull() {
            addCriterion("TOTALDAY is not null");
            return (Criteria) this;
        }

        public Criteria andTotaldayEqualTo(BigDecimal value) {
            addCriterion("TOTALDAY =", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayNotEqualTo(BigDecimal value) {
            addCriterion("TOTALDAY <>", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayGreaterThan(BigDecimal value) {
            addCriterion("TOTALDAY >", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALDAY >=", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayLessThan(BigDecimal value) {
            addCriterion("TOTALDAY <", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALDAY <=", value, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayIn(List<BigDecimal> values) {
            addCriterion("TOTALDAY in", values, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayNotIn(List<BigDecimal> values) {
            addCriterion("TOTALDAY not in", values, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALDAY between", value1, value2, "totalday");
            return (Criteria) this;
        }

        public Criteria andTotaldayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALDAY not between", value1, value2, "totalday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WST_CASHSWEEP
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}